# Generated by Django 3.2.22 on 2024-09-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0051_alter_employeecontract_contract_type'),
        ('sce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scemember',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sce_members', to='human_ressources.employee', unique=True),
        ),
    ]
