# Generated by Django 3.2.22 on 2024-09-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0003_alter_scemember_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='scemember',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'Président'), ('TRESORIER', 'Trésorier'), ('SECRETAIRE', 'Secrétaire'), ('MEMBRE', 'Membre'), ('SUPPLEANT', 'Suppléant')], default='MEMBRE', max_length=50),
        ),
    ]
