# Generated by Django 3.2.22 on 2024-09-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0005_scebenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scebenefit',
            name='content',
            field=models.TextField(default='', null=True),
        ),
    ]
