# Generated by Django 3.2.22 on 2024-09-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sce', '0006_scebenefit_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scemember',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'Président'), ('TREASURER', 'Trésorier'), ('ASSISTANT_TREASURER', 'Trésorier Adjoint'), ('SECRETARY', 'Secrétaire'), ('ASSISTANT_SECRETARY', 'Secrétaire Adjoint'), ('MEMBER', 'Membre'), ('SUBSTITUTE', 'Suppléant'), ('PRIMARY_MEMBER', 'Titulaire')], default='MEMBER', max_length=50),
        ),
    ]
