# Generated by Django 3.2.22 on 2024-03-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0010_auto_20240201_1012'),
        ('activities', '0004_auto_20240313_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbeneficiaryabsence',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder'),
        ),
    ]
