# Generated by Django 3.2.22 on 2024-03-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_eventbeneficiaryabsence_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbeneficiaryabsence',
            name='comment',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='eventbeneficiaryabsence',
            name='observation',
            field=models.TextField(default='', null=True),
        ),
    ]
