# Generated by Django 3.2.22 on 2024-03-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0020_remove_employeegroup_employees'),
        ('activities', '0006_auto_20240313_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_events', to='human_ressources.employee'),
        ),
    ]
