# Generated by Django 3.2.22 on 2024-03-14 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0010_auto_20240201_1012'),
        ('human_ressources', '0020_remove_employeegroup_employees'),
        ('activities', '0007_event_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventBeneficiaryAbsence',
            new_name='BeneficiaryAbsence',
        ),
    ]
