# Generated by Django 3.2.22 on 2024-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_rename_absencemotif_absencereason'),
        ('activities', '0009_auto_20240314_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryabsence',
            name='reasons',
            field=models.ManyToManyField(related_name='reason_beneficiary_absences', to='data_management.AbsenceReason'),
        ),
    ]
