# Generated by Django 3.2.22 on 2024-03-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_beneficiaryabsence_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryabsence',
            name='other_reasons',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
