# Generated by Django 3.2.22 on 2024-05-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_establishmentservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstablishmentService',
        ),
    ]
