# Generated by Django 3.2.22 on 2024-05-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_delete_establishmentservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryabsence',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
