# Generated by Django 3.2.22 on 2024-12-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_personalizedproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedproject',
            name='ending_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='personalizedproject',
            name='starting_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
