# Generated by Django 3.2.22 on 2025-01-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_auto_20241213_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryabsence',
            name='is_considered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
