# Generated by Django 3.2.22 on 2025-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_auto_20250123_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryexpense',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryexpense',
            name='check_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
