# Generated by Django 3.2.22 on 2025-01-24 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0071_auto_20250123_1445'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0048_auto_20250124_0940'),
        ('companies', '0035_companymedia_blog_url'),
        ('data_management', '0046_professionalstatus_typeendowment'),
        ('activities', '0022_auto_20250123_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndowmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('CREDIT_CARD', 'Carte de crédit'), ('BANK_TRANSFER', 'Virement bancaire'), ('DIRECT_DEBIT', 'Prélèvement'), ('PURCHASE_ORDER', 'Bon de commande'), ('CHECK', 'Chèque'), ('PAYPAL', 'PayPal'), ('BILL_OF_EXCHANGE', 'Lettre de change relevé'), ('LIBEO_TRANSFER', 'Virement par Libeo'), ('MOBILE_PAYMENT', 'Paiement mobile'), ('CRYPTOCURRENCY', 'Cryptomonnaie'), ('DEBIT_CARD', 'Carte de débit'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay')], default='CASH', max_length=50)),
                ('check_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En Attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('PAID', 'Payé')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('observation', models.TextField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bank_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endowment_payments', to='finance.bankcard')),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endowment_payments', to='human_ressources.beneficiary')),
                ('cash_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endowment_payments', to='finance.cashregister')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_endowment_payments', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_endowment_payments', to='human_ressources.employee')),
                ('endowment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endowment_payments', to='finance.endowment')),
                ('endowment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endowment_payments', to='data_management.typeendowment')),
            ],
        ),
    ]
