# Generated by Django 3.2.22 on 2025-01-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0013_contracttemplate_image'),
        ('activities', '0023_endowmentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='endowmentpayment',
            name='files',
            field=models.ManyToManyField(related_name='file_endowment_payments', to='medias.File'),
        ),
        migrations.AddField(
            model_name='endowmentpayment',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder'),
        ),
    ]
