# Generated by Django 3.2.22 on 2025-01-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0024_auto_20250124_1710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndowmentPayment',
        ),
    ]
