# Generated by Django 3.2.22 on 2025-03-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcandidate',
            old_name='interested_in',
            new_name='job_position',
        ),
    ]
