# Generated by Django 3.2.22 on 2025-03-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_rename_interested_in_jobcandidate_job_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcandidate',
            old_name='availability',
            new_name='availability_date',
        ),
    ]
