# Generated by Django 3.2.22 on 2025-03-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0049_jobplatform'),
        ('recruitment', '0003_rename_availability_jobcandidate_availability_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcandidate',
            old_name='job',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobcandidate',
            name='source',
        ),
        migrations.AddField(
            model_name='jobcandidate',
            name='job_platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.jobplatform'),
        ),
    ]
