# Generated by Django 3.2.22 on 2025-03-10 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0049_jobplatform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0007_remove_jobposting_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='job_platforms',
        ),
        migrations.CreateModel(
            name='JobPostingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_link', models.URLField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.jobplatform')),
                ('job_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_platforms', to='recruitment.jobposting')),
            ],
        ),
    ]
