# Generated by Django 3.2.22 on 2025-03-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_auto_20250310_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcandidate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('INTERESTED', 'Intéressant'), ('INTERVIEW', 'Entretien prévu'), ('OFFERED', 'Offre envoyée'), ('REJECTED', 'Rejeté'), ('ACCEPTED', 'Accepté')], default='PENDING', max_length=20),
        ),
    ]
