# Generated by Django 3.2.22 on 2025-03-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_alter_jobcandidateapplication_job_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcandidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Homme'), ('FEMALE', 'Femme'), ('NOT_SPECIFIED', 'Non spécifié')], default='NOT_SPECIFIED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobcandidate',
            name='preferred_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobcandidateapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Homme'), ('FEMALE', 'Femme'), ('NOT_SPECIFIED', 'Non spécifié')], default='NOT_SPECIFIED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobcandidateapplication',
            name='preferred_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
