# Generated by Django 3.2.22 on 2025-03-14 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_alter_establishment_measurement_activity_unit'),
        ('medias', '0017_rename_measurement_activity_unit_documentrecord_notification_period_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0083_advance'),
        ('recruitment', '0013_auto_20250313_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCandidateInformationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Homme'), ('FEMALE', 'Femme'), ('NOT_SPECIFIED', 'Non spécifié')], default='NOT_SPECIFIED', max_length=50, null=True)),
                ('preferred_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=255)),
                ('description', models.TextField(default='', null=True)),
                ('observation', models.TextField(default='', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('REJECTED', 'Rejeté'), ('ACCEPTED', 'Accepté')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_job_candidate_information_sheets', to='companies.company')),
                ('cover_letter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letter_job_candidate_information_sheets', to='medias.file')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_candidate_information_sheets', to=settings.AUTH_USER_MODEL)),
                ('cv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_job_candidate_information_sheets', to='medias.file')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_candidate_information_sheets', to='human_ressources.employee')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder')),
                ('job_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_candidate_information_sheets', to='recruitment.jobcandidate')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.jobposition')),
            ],
        ),
    ]
