# Generated by Django 3.2.22 on 2025-03-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_auto_20250317_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcandidateinformationsheet',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobcandidateinformationsheet',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
