# Generated by Django 3.2.22 on 2025-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_auto_20250317_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('REJECTED', 'Rejeté'), ('ACCEPTED', 'Accepté')], default='PENDING', max_length=20),
        ),
    ]
