# Generated by Django 3.2.22 on 2025-03-18 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0017_jobposition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcandidateapplication',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_job_candidate_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
