# Generated by Django 3.2.22 on 2025-03-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_alter_jobcandidateapplication_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcandidateinformationsheet',
            old_name='message',
            new_name='comment',
        ),
    ]
