# Generated by Django 3.2.22 on 2025-03-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_auto_20250321_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcandidateinformationsheet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('REJECTED', 'Rejeté'), ('ACCEPTED', 'Accepté')], default='PENDING', max_length=20),
        ),
    ]
