# Generated by Django 3.2.22 on 2024-05-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_decisiondocumentitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decisiondocument',
            old_name='reception_date',
            new_name='reception_date_time',
        ),
    ]
