# Generated by Django 3.2.22 on 2024-05-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_reception_date_decisiondocument_reception_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiondocumentitem',
            name='theoretical_number_unit_work',
            field=models.FloatField(null=True),
        ),
    ]
