# Generated by Django 3.2.22 on 2024-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_decisiondocumentitem_theoretical_number_unit_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiondocumentitem',
            name='occupancy_rate',
            field=models.FloatField(null=True),
        ),
    ]
