# Generated by Django 3.2.22 on 2024-05-17 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0006_financier'),
        ('finance', '0005_decisiondocumentitem_occupancy_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiondocumentitem',
            name='financier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.financier'),
        ),
    ]
