# Generated by Django 3.2.22 on 2024-05-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20240517_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiondocument',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
