# Generated by Django 3.2.22 on 2024-05-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20240522_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('CURRENT', 'Courant'), ('SAVINGS', 'Placement'), ('FIXED_TERM', 'Compte à terme')], default='CURRENT', max_length=50),
        ),
    ]
