# Generated by Django 3.2.22 on 2024-05-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0011_file_company'),
        ('finance', '0012_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder'),
        ),
    ]
