# Generated by Django 3.2.22 on 2024-05-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_remove_balance_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
