# Generated by Django 3.2.22 on 2024-05-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiondocumentitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
