# Generated by Django 3.2.22 on 2024-05-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_decisiondocumentitem_endowment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiondocumentitem',
            name='decision_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_document_items', to='finance.decisiondocument'),
        ),
    ]
