# Generated by Django 3.2.22 on 2024-06-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_decisiondocumentitem_decision_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='folder',
        ),
    ]
