# Generated by Django 3.2.22 on 2024-11-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_auto_20241112_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente de validation'), ('APPROVED', 'Validé'), ('REJECTED', 'Rejeté'), ('IN_PROGRESS', 'En cours'), ('PARTIALLY_USED', 'Partiellement utilisé'), ('COMPLETED', 'Complété'), ('OVERSPENT', 'Dépassement'), ('ON_HOLD', 'En attente'), ('CANCELLED', 'Annulé'), ('CLOSED', 'Clôturé')], default='DRAFT', max_length=20),
        ),
    ]
