# Generated by Django 3.2.22 on 2024-11-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_alter_company_status'),
        ('data_management', '0034_accountingnature'),
        ('finance', '0027_auto_20241112_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='accounting_nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='data_management.accountingnature'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='companies.establishment'),
        ),
    ]
