# Generated by Django 3.2.22 on 2024-11-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_alter_expense_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='accounting_nature',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='expense',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='ExpenseItem',
        ),
    ]
