# Generated by Django 3.2.22 on 2024-11-27 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0036_auto_20241126_1114'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0030_auto_20241113_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAccountingNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('accounting_nature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_accounting_natures', to='data_management.accountingnature')),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_natures', to='finance.budget')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_accounting_natures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
