# Generated by Django 3.2.22 on 2024-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_budgetaccountingnature'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetaccountingnature',
            name='amount_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
