# Generated by Django 3.2.22 on 2024-11-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_auto_20241127_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetaccountingnature',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_accounting_natures', to='finance.budget'),
        ),
    ]
