# Generated by Django 3.2.22 on 2024-12-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_cashregister_cashregisterestablishment_cashregistermanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='balance',
        ),
    ]
