# Generated by Django 3.2.22 on 2024-12-05 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0057_employeecontractreplacedemployee_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0036_remove_cashregister_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregistermanager',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_register_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashregistermanager',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_register_employees', to='human_ressources.employee'),
        ),
        migrations.CreateModel(
            name='CashRegisterTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], default='CREDIT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cash_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.cashregister')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_register_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
