# Generated by Django 3.2.22 on 2024-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_auto_20241205_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregistertransaction',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cashregistertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Encaissement'), ('DEBIT', 'Décaissement')], default='CREDIT', max_length=50),
        ),
    ]
