# Generated by Django 3.2.22 on 2024-12-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0024_remove_expenseitem_establishment'),
        ('finance', '0039_auto_20241206_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregistertransaction',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_register_transactions', to='purchases.expense'),
        ),
    ]
