# Generated by Django 3.2.22 on 2024-12-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0057_employeecontractreplacedemployee_position'),
        ('finance', '0040_cashregistertransaction_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetaccountingnature',
            name='managers',
            field=models.ManyToManyField(related_name='budget_accounting_natures', to='human_ressources.Employee'),
        ),
    ]
