# Generated by Django 3.2.22 on 2025-01-13 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0035_companymedia_blog_url'),
        ('finance', '0041_budgetaccountingnature_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiondocumentitem',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_document_items', to='companies.establishment'),
        ),
    ]
