# Generated by Django 3.2.22 on 2025-01-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0043_endowment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endowment',
            old_name='name',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='endowment',
            name='age_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Âge maximum'),
        ),
        migrations.AlterField(
            model_name='endowment',
            name='age_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Âge minimum'),
        ),
    ]
