# Generated by Django 3.2.22 on 2025-01-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0044_auto_20250120_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endowment',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Homme'), ('FEMALE', 'Femme'), ('NOT_SPECIFIED', 'Non spécifié')], default='NOT_SPECIFIED', max_length=50, null=True),
        ),
    ]
