# Generated by Django 3.2.22 on 2025-01-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0046_bankcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='observation',
            field=models.TextField(default='', null=True),
        ),
    ]
