# Generated by Django 3.2.22 on 2025-01-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0049_endowmentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='endowmentpayment',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endowmentpayment',
            name='number',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
