# Generated by Django 3.2.22 on 2025-01-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0050_auto_20250127_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='endowmentpayment',
            name='bic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endowmentpayment',
            name='iban',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
