# Generated by Django 3.2.22 on 2025-01-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0051_auto_20250128_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregistertransaction',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
