# Generated by Django 3.2.22 on 2024-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_rename_absencemotif_absencereason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencereason',
            name='descreption',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='undesirableeventtype',
            name='descreption',
            field=models.TextField(default='', null=True),
        ),
    ]
