# Generated by Django 3.2.22 on 2024-04-02 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_management', '0007_meetingreason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absencereason',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='meetingreason',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='undesirableeventfrequency',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='undesirableeventnormaltype',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='undesirableeventserioustype',
            old_name='descreption',
            new_name='description',
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('number', models.CharField(max_length=255)),
                ('description', models.TextField(default='', null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(default='', null=True)),
                ('description', models.TextField(default='', null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
