# Generated by Django 3.2.22 on 2024-04-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0009_rename_number_phonenumber_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
