# Generated by Django 3.2.22 on 2024-04-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0010_rename_phone_number_phonenumber_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaddress',
            name='name',
            field=models.CharField(default='Sans nom', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='name',
            field=models.CharField(default='Sans nom', max_length=255, null=True),
        ),
    ]
