# Generated by Django 3.2.22 on 2024-05-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_delete_establishmentservice'),
        ('data_management', '0016_establishmentservicetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstablishmentServiceType',
        ),
    ]
