# Generated by Django 3.2.22 on 2024-05-23 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0021_meeting_meeting_types'),
        ('companies', '0023_alter_activityauthorization_establishment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_management', '0020_meetingtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingType',
            new_name='TypeMeeting',
        ),
    ]
