# Generated by Django 3.2.22 on 2024-06-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0041_alter_employeecontract_contract_type'),
        ('data_management', '0022_vehiclebrand_vehiclemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeContractType',
        ),
    ]
