# Generated by Django 3.2.22 on 2024-10-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0025_customfield_customfieldvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('RADIO', 'Radio Button'), ('SELECT', 'Select'), ('CHECKBOX', 'Checkbox')], default='TEXT', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='data_management.customfield')),
            ],
        ),
    ]
