# Generated by Django 3.2.22 on 2024-10-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0026_auto_20241008_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='form_model',
            field=models.CharField(choices=[('EMPLOYEE', 'Employé'), ('EMPLOYEE_CONTRACT', 'Contrat Employé')], max_length=50),
        ),
    ]
