# Generated by Django 3.2.22 on 2024-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0027_alter_customfield_form_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldoption',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
