# Generated by Django 3.2.22 on 2024-10-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0028_alter_customfieldoption_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='form_model',
            field=models.CharField(choices=[('Employee', 'Employé'), ('EmployeeContract', 'Contrat Employé')], max_length=50),
        ),
    ]
