# Generated by Django 3.2.22 on 2024-11-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0034_accountingnature'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencereason',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='absencereason',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='absencereason',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.absencereason'),
        ),
        migrations.AddField(
            model_name='accountingnature',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountingnature',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountingnature',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.accountingnature'),
        ),
        migrations.AddField(
            model_name='admissiondocumenttype',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissiondocumenttype',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissiondocumenttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.admissiondocumenttype'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.documenttype'),
        ),
        migrations.AddField(
            model_name='employeemission',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeemission',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeemission',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.employeemission'),
        ),
        migrations.AddField(
            model_name='establishmentcategory',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='establishmentcategory',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='establishmentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.establishmentcategory'),
        ),
        migrations.AddField(
            model_name='establishmenttype',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='establishmenttype',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='establishmenttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.establishmenttype'),
        ),
        migrations.AddField(
            model_name='humangender',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='humangender',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='humangender',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.humangender'),
        ),
        migrations.AddField(
            model_name='meetingreason',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingreason',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingreason',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.meetingreason'),
        ),
        migrations.AddField(
            model_name='typemeeting',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typemeeting',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typemeeting',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.typemeeting'),
        ),
        migrations.AddField(
            model_name='undesirableeventfrequency',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='undesirableeventfrequency',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='undesirableeventfrequency',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.undesirableeventfrequency'),
        ),
        migrations.AddField(
            model_name='undesirableeventnormaltype',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='undesirableeventnormaltype',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='undesirableeventnormaltype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.undesirableeventnormaltype'),
        ),
        migrations.AddField(
            model_name='undesirableeventserioustype',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='undesirableeventserioustype',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='undesirableeventserioustype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.undesirableeventserioustype'),
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.vehiclebrand'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_management.vehiclemodel'),
        ),
    ]
