# Generated by Django 3.2.22 on 2024-12-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0038_auto_20241203_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingnature',
            name='replaced_accounting_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='data_management.accountingnature'),
        ),
    ]
