# Generated by Django 3.2.22 on 2024-12-04 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0039_accountingnature_replaced_accounting_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingnature',
            name='replaced_accounting_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_accounting_natures', to='data_management.accountingnature'),
        ),
    ]
