# Generated by Django 3.2.22 on 2024-12-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0059_beneficiarystatusentry'),
        ('data_management', '0041_beneficiarystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldvalue',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_field_values', to='human_ressources.beneficiary'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='form_model',
            field=models.CharField(choices=[('Employee', 'Employé'), ('EmployeeContract', 'Contrat Employé'), ('Beneficiary', 'Personne accompagnée')], max_length=50),
        ),
    ]
