# Generated by Django 3.2.22 on 2024-12-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0042_auto_20241216_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Zone du text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('DATETIME', 'Date et heure'), ('BOOLEAN', 'Boolean'), ('RADIO', 'Radio Button'), ('SELECT', 'Liste'), ('SELECT_MULTIPLE', 'Liste à choix multiple'), ('CHECKBOX', 'Checkbox')], default='TEXT', max_length=50),
        ),
    ]
