# Generated by Django 3.2.22 on 2023-12-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='author_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='author_number',
            field=models.TextField(null=True),
        ),
    ]
