# Generated by Django 3.2.22 on 2024-01-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_auto_20231208_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='author_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
