# Generated by Django 3.2.22 on 2024-02-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_signature_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='comment',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='satisfaction',
            field=models.CharField(choices=[('ANGRY', 'ANGRY'), ('CONFUSED', 'CONFUSED'), ('SMILE', 'SMILE'), ('KISS', 'KISS')], default='MEDIUM', max_length=50),
        ),
    ]
