# Generated by Django 3.2.22 on 2024-02-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_alter_signature_satisfaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='satisfaction',
            field=models.CharField(choices=[('NONE', 'NONE'), ('ANGRY', 'ANGRY'), ('CONFUSED', 'CONFUSED'), ('SMILE', 'SMILE'), ('KISS', 'KISS')], default='NONE', max_length=50),
        ),
    ]
