# Generated by Django 3.2.22 on 2024-05-14 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0022_delete_undesirableeventestablishmentservice'),
        ('feedbacks', '0009_alter_signature_satisfaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'À faire'), ('STARTED', 'En cours'), ('FINISHED', 'Terminée'), ('PENDING', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='NEW', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('undesirable_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='qualities.undesirableevent')),
            ],
        ),
    ]
