# Generated by Django 3.2.22 on 2024-06-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0010_statuschange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuschange',
            name='status',
        ),
        migrations.AddField(
            model_name='statuschange',
            name='name',
            field=models.CharField(default='NEW', max_length=255, null=True),
        ),
    ]
