# Generated by Django 3.2.22 on 2024-07-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_module',
            field=models.CharField(choices=[('APP', 'Application'), ('REMINDER', 'Rappel'), ('MESSAGE', 'Message'), ('TASK', 'Tâche'), ('EVENT', 'Événement'), ('NEWS', 'Actualités'), ('WARNING', 'Avertissement'), ('PROMOTION', 'Promotion'), ('UPDATE', 'Mise à jour'), ('FEEDBACK', 'Commentaires'), ('ERROR', 'Erreur')], default='APP', max_length=50),
        ),
    ]
