# Generated by Django 3.2.22 on 2024-07-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0013_feedback_feedback_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_module',
            field=models.CharField(choices=[('APP', 'Application'), ('DASHBOARD', 'Tableau de bord'), ('QUALITY', 'Qualité'), ('ACTIVITY', 'Activité'), ('HR', 'Ressources Humaines'), ('ADMINISTRATIF', 'Administratif'), ('FACILITY', 'Services Généraux'), ('FINANCE', 'Finance'), ('IT', 'Informatique'), ('PURCHASE', 'Achat'), ('GOVERNANCE', 'Gouvernance'), ('CSE', 'CSE'), ('LEGAL', 'Juridiques'), ('RESOURCES', 'Ressources'), ('USERS', 'Utilisateurs'), ('SETTINGS', 'Paramètres')], default='APP', max_length=50),
        ),
    ]
