# Generated by Django 3.2.22 on 2024-11-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_expense_expenseitem'),
        ('feedbacks', '0015_auto_20241003_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='purchases.expense'),
        ),
    ]
