# Generated by Django 3.2.22 on 2024-11-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0038_auto_20241022_1041'),
        ('feedbacks', '0016_comment_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='task_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='works.taskaction'),
        ),
    ]
