# Generated by Django 3.2.22 on 2024-12-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0063_alter_beneficiaryadmission_files'),
        ('feedbacks', '0017_comment_task_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='beneficiary_admission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='human_ressources.beneficiaryadmission'),
        ),
    ]
