# Generated by Django 3.2.22 on 2025-01-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0065_employee_signature'),
        ('feedbacks', '0018_comment_beneficiary_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='author_position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='human_ressources.employee'),
        ),
    ]
