# Generated by Django 3.2.22 on 2025-04-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_alter_employeeabsence_status'),
        ('feedbacks', '0019_auto_20250114_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='employee_absence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='planning.employeeabsence'),
        ),
    ]
