# Generated by Django 3.2.22 on 2024-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0002_auto_20240328_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_type',
            field=models.CharField(choices=[('INCOMING', 'Entrant'), ('OUTGOING', 'Sortant')], default='INCOMING', max_length=50, null=True),
        ),
    ]
