# Generated by Django 3.2.22 on 2024-03-28 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0020_remove_employeegroup_employees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administratives', '0005_rename_comment_meeting_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantMeetingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_meeting_item_former', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_meeting_items', to='human_ressources.employee')),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administratives.meeting')),
            ],
        ),
    ]
