# Generated by Django 3.2.22 on 2024-04-02 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_client_address'),
        ('partnerships', '0005_alter_partner_address'),
        ('human_ressources', '0020_remove_employeegroup_employees'),
        ('data_management', '0008_auto_20240402_1100'),
        ('companies', '0009_establishment_establishment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0006_alter_supplier_address'),
        ('administratives', '0009_meetingreport_meetingreportitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_beneficiary_callers', to='human_ressources.beneficiary')),
                ('call', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administratives.call')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_client_callers', to='sales.client')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_caller_former', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_employee_callers', to='human_ressources.employee')),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_establishment_callers', to='companies.establishment')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_partner_callers', to='partnerships.partner')),
                ('phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_phone_number_callers', to='data_management.phonenumber')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_supplier_callers', to='purchases.supplier')),
            ],
        ),
    ]
