# Generated by Django 3.2.22 on 2024-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0011_caller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
