# Generated by Django 3.2.22 on 2024-04-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0012_caller_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='caller_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
