# Generated by Django 3.2.22 on 2024-04-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0013_caller_caller_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingreportitem',
            old_name='comment',
            new_name='decision',
        ),
        migrations.RenameField(
            model_name='meetingreportitem',
            old_name='description',
            new_name='points_to_review',
        ),
        migrations.RenameField(
            model_name='meetingreportitem',
            old_name='name',
            new_name='report',
        ),
        migrations.RemoveField(
            model_name='meetingreportitem',
            name='number',
        ),
        migrations.RemoveField(
            model_name='meetingreportitem',
            name='observation',
        ),
    ]
