# Generated by Django 3.2.22 on 2024-05-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0014_auto_20240405_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
