# Generated by Django 3.2.22 on 2024-05-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_alter_activityauthorization_establishment'),
        ('administratives', '0016_auto_20240520_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_meetings', to='companies.establishment'),
        ),
    ]
