# Generated by Django 3.2.22 on 2024-05-23 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0023_alter_activityauthorization_establishment'),
        ('administratives', '0018_meeting_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='establishment',
        ),
        migrations.CreateModel(
            name='MeetingEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_establishment_former', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_establishment', to='companies.establishment')),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administratives.meeting')),
            ],
        ),
    ]
