# Generated by Django 3.2.22 on 2024-05-23 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0037_employeecontract_folder'),
        ('companies', '0023_alter_activityauthorization_establishment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administratives', '0019_auto_20240523_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_beneficiaries', to='human_ressources.beneficiary')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_beneficiary_former', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_meeting_former', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_meetings', to='human_ressources.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='participantmeetingitem',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='participantmeetingitem',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='participantmeetingitem',
            name='meeting',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_meeting_beneficiarys', to='companies.company'),
        ),
        migrations.DeleteModel(
            name='BeneficiaryMeetingItem',
        ),
        migrations.DeleteModel(
            name='ParticipantMeetingItem',
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administratives.meeting'),
        ),
        migrations.AddField(
            model_name='meetingbeneficiary',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administratives.meeting'),
        ),
    ]
