# Generated by Django 3.2.22 on 2024-05-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0020_meetingtype'),
        ('administratives', '0020_auto_20240523_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_types',
            field=models.ManyToManyField(related_name='type_meetings', to='data_management.MeetingType'),
        ),
    ]
