# Generated by Django 3.2.22 on 2024-05-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0022_auto_20240523_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingreviewpoint',
            old_name='points_to_review',
            new_name='point_to_review',
        ),
    ]
