# Generated by Django 3.2.22 on 2024-05-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0037_employeecontract_folder'),
        ('administratives', '0024_meetingdecision_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingdecision',
            name='employees',
            field=models.ManyToManyField(related_name='employeemeeting_decisions', to='human_ressources.Employee'),
        ),
    ]
