# Generated by Django 3.2.22 on 2024-05-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0037_employeecontract_folder'),
        ('administratives', '0025_meetingdecision_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='present_participants',
            field=models.ManyToManyField(related_name='present_participant_meetings', to='human_ressources.Employee'),
        ),
        migrations.AlterField(
            model_name='meetingdecision',
            name='employees',
            field=models.ManyToManyField(related_name='employee_meeting_decisions', to='human_ressources.Employee'),
        ),
    ]
