# Generated by Django 3.2.22 on 2024-05-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0026_auto_20240523_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='notes',
            field=models.TextField(default='', null=True),
        ),
    ]
