# Generated by Django 3.2.22 on 2024-05-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0037_employeecontract_folder'),
        ('administratives', '0027_meeting_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='present_participants',
        ),
        migrations.AddField(
            model_name='meeting',
            name='absent_participants',
            field=models.ManyToManyField(related_name='absent_participant_meetings', to='human_ressources.Employee'),
        ),
    ]
