# Generated by Django 3.2.22 on 2024-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0028_auto_20240525_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=50),
        ),
    ]
