# Generated by Django 3.2.22 on 2024-05-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0029_meetingparticipant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
