# Generated by Django 3.2.22 on 2024-05-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0030_auto_20240525_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_mode',
            field=models.CharField(choices=[('PV', 'Procès-Verbal'), ('SIMPLE', 'Réunion Simple')], default='SIMPLE', max_length=50),
        ),
    ]
