# Generated by Django 3.2.22 on 2024-05-31 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0032_auto_20240528_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingbeneficiary',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='administratives.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingdecision',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_decisions', to='administratives.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingestablishment',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to='administratives.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='administratives.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingreviewpoint',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_review_points', to='administratives.meeting'),
        ),
    ]
