# Generated by Django 3.2.22 on 2024-06-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0035_auto_20240624_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_create_undesirable_event_from',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
