# Generated by Django 3.2.22 on 2024-06-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0037_document'),
        ('human_ressources', '0046_auto_20240626_1010'),
        ('data_management', '0024_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='data_management.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='human_ressources.employee'),
        ),
    ]
