# Generated by Django 3.2.22 on 2024-09-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0039_auto_20240628_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_mode',
            field=models.CharField(choices=[('PV', 'Procès-Verbal'), ('SCE', 'Procès-Verbal cse'), ('SIMPLE', 'Réunion Simple')], default='SIMPLE', max_length=50),
        ),
    ]
