# Generated by Django 3.2.22 on 2024-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0041_alter_meeting_meeting_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_mode',
            field=models.CharField(choices=[('PV', 'Procès-Verbal'), ('PV_SCE', 'Procès-Verbal cse'), ('SIMPLE', 'Réunion Simple'), ('INTERVIEW', 'Entretien')], default='SIMPLE', max_length=50),
        ),
    ]
