# Generated by Django 3.2.22 on 2024-11-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0013_contracttemplate_image'),
        ('administratives', '0042_alter_meeting_meeting_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='image',
        ),
        migrations.AddField(
            model_name='letter',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_letters', to='medias.file'),
        ),
    ]
