# Generated by Django 3.2.22 on 2024-12-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_auto_20241125_1105'),
        ('administratives', '0043_auto_20241121_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='framedocument',
            name='establishments',
            field=models.ManyToManyField(related_name='frame_documents', to='companies.Establishment'),
        ),
    ]
