# Generated by Django 3.2.22 on 2025-01-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0044_framedocument_establishments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='topic',
        ),
        migrations.AddField(
            model_name='meeting',
            name='topics',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
