# Generated by Django 3.2.22 on 2025-03-05 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0042_auto_20250123_1128'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0082_auto_20250227_1008'),
        ('partnerships', '0009_auto_20241212_1520'),
        ('administratives', '0045_auto_20250129_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('sender_type', models.CharField(max_length=255, null=True)),
                ('other_sender', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_sender_former', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_employee_senders', to='human_ressources.employee')),
                ('financier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_financier_senders', to='partnerships.financier')),
                ('letter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders', to='administratives.letter')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_partner_senders', to='partnerships.partner')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_supplier_senders', to='purchases.supplier')),
            ],
        ),
    ]
