# Generated by Django 3.2.22 on 2025-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0046_lettersender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_mode',
            field=models.CharField(choices=[('PV', 'Procès-Verbal'), ('PV_SCE', 'Procès-Verbal cse'), ('SIMPLE', 'Réunion Simple'), ('INTERVIEW', 'Entretien'), ('CANDIDATE_INTERVIEW', 'Entretien Candidat')], default='SIMPLE', max_length=50),
        ),
    ]
