# Generated by Django 3.2.22 on 2025-03-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_auto_20250313_1127'),
        ('administratives', '0047_alter_meeting_meeting_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='job_candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_candidate_meetings', to='recruitment.jobcandidate'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='job_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_position_meetings', to='recruitment.jobposition'),
        ),
    ]
