# Generated by Django 3.2.22 on 2025-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0048_auto_20250313_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='framedocument',
            name='document_scope',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('GOVERNANCE', 'Gouvernance')], default='NORMAL', max_length=50),
        ),
    ]
