# Generated by Django 3.2.22 on 2024-02-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_supplier_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='external_number',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
