# Generated by Django 3.2.22 on 2024-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_supplier_external_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(default='', null=True),
        ),
    ]
