# Generated by Django 3.2.22 on 2024-11-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_auto_20241113_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='expense_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
