# Generated by Django 3.2.22 on 2024-11-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_auto_20241119_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='label',
        ),
    ]
