# Generated by Django 3.2.22 on 2024-11-19 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0030_alter_company_status'),
        ('purchases', '0012_rename_name_expense_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_establishments', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_establishments', to='companies.establishment')),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to='purchases.expense')),
            ],
        ),
    ]
