# Generated by Django 3.2.22 on 2024-11-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0013_contracttemplate_image'),
        ('purchases', '0013_expenseestablishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder'),
        ),
    ]
