# Generated by Django 3.2.22 on 2024-11-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0013_contracttemplate_image'),
        ('purchases', '0014_expense_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='files',
            field=models.ManyToManyField(related_name='file_expenses', to='medias.File'),
        ),
    ]
