# Generated by Django 3.2.22 on 2024-11-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_alter_expense_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('INVESTMENT', 'Investissement'), ('PURCHASE', 'Achat')], default='PURCHASE', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_amount_accurate',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_planned_in_budget',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
