# Generated by Django 3.2.22 on 2024-11-28 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_auto_20241128_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_expenses', to='purchases.supplier'),
        ),
    ]
