# Generated by Django 3.2.22 on 2024-12-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0023_expenseitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='establishment',
        ),
    ]
