# Generated by Django 3.2.22 on 2024-12-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0040_cashregistertransaction_expense'),
        ('purchases', '0024_remove_expenseitem_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cash_register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_register_expenses', to='finance.cashregister'),
        ),
    ]
