# Generated by Django 3.2.22 on 2024-12-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0057_employeecontractreplacedemployee_position'),
        ('purchases', '0027_purchaseorder_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='human_ressources.employee'),
        ),
    ]
