# Generated by Django 3.2.22 on 2024-12-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0028_purchaseorder_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='purchases.expense'),
        ),
    ]
