# Generated by Django 3.2.22 on 2024-12-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0030_rename_amount_purchaseorderitem_amount_ttc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at']},
        ),
    ]
