# Generated by Django 3.2.22 on 2024-12-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0031_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='total_amount',
            new_name='total_ttc',
        ),
    ]
