# Generated by Django 3.2.22 on 2024-12-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0032_rename_total_amount_purchaseorder_total_ttc'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='validity_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
