# Generated by Django 3.2.22 on 2024-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0034_purchaseorder_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='additional_address',
            field=models.TextField(default='', null=True),
        ),
    ]
