# Generated by Django 3.2.22 on 2024-12-23 14:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0035_companymedia_blog_url'),
        ('human_ressources', '0060_beneficiaryentry_due_date'),
        ('medias', '0013_contracttemplate_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0036_purchasecontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('expense_date_time', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('CREDIT_CARD', 'Carte de crédit'), ('BANK_TRANSFER', 'Virement bancaire'), ('DIRECT_DEBIT', 'Prélèvement'), ('PURCHASE_ORDER', 'Bon de commande'), ('CHECK', 'Chèque'), ('PAYPAL', 'PayPal'), ('BILL_OF_EXCHANGE', 'Lettre de change relevé'), ('LIBEO_TRANSFER', 'Virement par Libeo'), ('MOBILE_PAYMENT', 'Paiement mobile'), ('CRYPTOCURRENCY', 'Cryptomonnaie'), ('DEBIT_CARD', 'Carte de débit'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay')], default='CREDIT_CARD', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('NEW', 'Nouveau'), ('PENDING', 'En Attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('REJECTED', 'Rejeté'), ('REIMBURSED', 'Remboursé')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('observation', models.TextField(blank=True, default='', null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_expense_reports', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_expense_reports', to='human_ressources.employee')),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_expense_reports', to='companies.establishment')),
                ('files', models.ManyToManyField(related_name='file_expense_reports', to='medias.File')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder')),
            ],
        ),
    ]
