# Generated by Django 3.2.22 on 2024-12-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0037_expensereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('NEW', 'Nouveau'), ('PENDING', 'En Attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('REIMBURSED', 'Remboursé')], default='PENDING', max_length=20),
        ),
    ]
