# Generated by Django 3.2.22 on 2025-01-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0038_alter_expensereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_verified',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
