# Generated by Django 3.2.22 on 2025-01-23 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0047_auto_20250123_0940'),
        ('purchases', '0040_alter_supplier_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bank_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_card_expenses', to='finance.bankcard'),
        ),
    ]
