# Generated by Django 3.2.22 on 2025-02-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20250225_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcomment',
            name='comment_type',
            field=models.CharField(choices=[('SYNTHESIS', 'Synthesis'), ('ACTIVITY', 'Activity'), ('GRAPH', 'Graph'), ('OTHER', 'Other')], default='INCOMING', max_length=50, null=True),
        ),
    ]
