# Generated by Django 3.2.22 on 2025-02-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboardcomment_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcomment',
            name='comment_type',
            field=models.CharField(choices=[('SYNTHESIS', 'Synthesis'), ('ACTIVITY', 'Activity'), ('GRAPH', 'Graph'), ('OTHER', 'Other')], default='SYNTHESIS', max_length=50, null=True),
        ),
    ]
