# Generated by Django 3.2.22 on 2023-10-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20231025_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('PRO', 'Pro'), ('STANDARD', 'standard')], default='PRO', max_length=50, null=True),
        ),
    ]
