# Generated by Django 3.2.22 on 2023-12-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_longitude',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
