# Generated by Django 3.2.22 on 2024-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_device_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.TextField(max_length=255),
        ),
    ]
