# Generated by Django 3.2.22 on 2024-05-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0029_auto_20240520_1043'),
        ('accounts', '0010_auto_20240520_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_ressources.employee'),
        ),
    ]
