# Generated by Django 3.2.22 on 2024-05-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usercompany_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompany',
            name='is_deleted',
        ),
    ]
