# Generated by Django 3.2.22 on 2024-06-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_device_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=5),
        ),
    ]
