# Generated by Django 3.2.22 on 2024-06-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20240607_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tokens',
        ),
        migrations.AddField(
            model_name='user',
            name='number_current_openai_tokens',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_current_connexions',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
