# Generated by Django 3.2.22 on 2024-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20240613_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('QUALITY_MANAGER', 'Responsable Qualité'), ('FACILITY_MANAGER', 'Responsable Services Généraux'), ('EMPLOYEE', 'Employee'), ('MECHANIC', 'Garagiste')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.Role'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='managed_companies', to='accounts.Role'),
        ),
    ]
