# Generated by Django 3.2.22 on 2024-06-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Employé'), ('QUALITY_MANAGER', 'Responsable Qualité'), ('FACILITY_MANAGER', 'Responsable Services Généraux'), ('EMPLOYEE', 'Employee'), ('MECHANIC', 'Garagiste')], max_length=100, unique=True),
        ),
    ]
