# Generated by Django 3.2.22 on 2024-07-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Employé'), ('QUALITY_MANAGER', 'Responsable Qualité'), ('ACTIVITY_MANAGER', 'Responsable Activité'), ('ADMINISTRATIVE_MANAGER', 'Responsable Administratif'), ('HR_MANAGER', 'Responsable RH'), ('FACILITY_MANAGER', 'Responsable Services Généraux'), ('FINANCE_MANAGER', 'Responsable Finance'), ('EMPLOYEE', 'Employee'), ('MECHANIC', 'Garagiste')], max_length=100, unique=True),
        ),
    ]
