# Generated by Django 3.2.22 on 2024-07-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0008_auto_20240520_1043'),
        ('human_ressources', '0047_employee_social_security_number'),
        ('accounts', '0021_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to='human_ressources.employee'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='financier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to='partnerships.financier'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to='partnerships.partner'),
        ),
    ]
