# Generated by Django 3.2.22 on 2024-10-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_alter_company_status'),
        ('purchases', '0008_supplier_company'),
        ('accounts', '0023_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_users', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to='purchases.supplier'),
        ),
    ]
