# Generated by Django 3.2.22 on 2025-03-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_must_change_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='must_change_password',
            new_name='is_must_change_password',
        ),
    ]
