# Generated by Django 3.2.22 on 2025-04-15 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
