# Generated by Django 3.2.22 on 2025-06-02 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_alter_governancemember_role'),
        ('accounts', '0031_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='governance_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_member_user', to='governance.governancemember'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='governance_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to='governance.governancemember'),
        ),
    ]
