# Generated by Django 3.2.22 on 2024-06-18 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0022_vehiclebrand_vehiclemodel'),
        ('medias', '0011_file_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0026_auto_20240530_1515'),
        ('human_ressources', '0038_auto_20240530_1526'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeabsence',
            name='absence_type',
            field=models.CharField(choices=[('ANNUAL', 'Congé Annuel'), ('SICK', 'Congé Maladie'), ('MATERNITY', 'Congé Maternité'), ('PATERNITY', 'Congé Paternité'), ('UNPAID', 'Congé Sans Solde'), ('PARENTAL', 'Congé Parental'), ('BEREAVEMENT', 'Congé de Décès'), ('MARRIAGE', 'Congé de Mariage'), ('STUDY', 'Congé de Formation'), ('ADOPTION', "Congé d'Adoption")], default='ABSENCE', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_absences', to='medias.file'),
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL', 'Congé Annuel'), ('SICK', 'Congé Maladie'), ('MATERNITY', 'Congé Maternité'), ('PATERNITY', 'Congé Paternité'), ('UNPAID', 'Congé Sans Solde'), ('PARENTAL', 'Congé Parental'), ('BEREAVEMENT', 'Congé de Décès'), ('MARRIAGE', 'Congé de Mariage'), ('STUDY', 'Congé de Formation'), ('ADOPTION', "Congé d'Adoption")], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En Attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeabsence',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_absences', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='employeeabsence',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeabsence',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_absences', to='human_ressources.employee'),
        ),
        migrations.AlterField(
            model_name='employeeabsence',
            name='reasons',
            field=models.ManyToManyField(related_name='employee_absences', to='data_management.AbsenceReason'),
        ),
        migrations.AlterField(
            model_name='employeeabsenceitem',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_absence_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeabsenceitem',
            name='employee_absence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='planning.employeeabsence'),
        ),
    ]
