# Generated by Django 3.2.22 on 2024-06-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_rename_absence_type_employeeabsence_absence_typo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeabsence',
            old_name='absence_typo',
            new_name='absence_type',
        ),
    ]
