# Generated by Django 3.2.22 on 2024-06-20 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0006_alter_employeeabsence_absence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeabsence',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employee_absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='rejected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_employee_absences', to=settings.AUTH_USER_MODEL),
        ),
    ]
