# Generated by Django 3.2.22 on 2024-06-20 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0007_auto_20240620_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeabsence',
            name='put_on_hold_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='put_on_hold_by_employee_absences', to=settings.AUTH_USER_MODEL),
        ),
    ]
