# Generated by Django 3.2.22 on 2024-06-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_employeeabsence_put_on_hold_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeabsence',
            name='absence_type',
        ),
    ]
