# Generated by Django 3.2.22 on 2024-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_remove_employeeabsence_absence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsence',
            name='leave_type',
            field=models.CharField(choices=[('PAID', 'Congés payés (CP)'), ('UNPAID', 'Congé Sans Solde'), ('RWT', 'Temps de Travail Réduit (RTT)'), ('TEMPORARY', 'Congé Temporaire (CT)'), ('ANNUAL', 'Congé Annuel'), ('SICK', 'Congé Maladie'), ('MATERNITY', 'Congé Maternité'), ('PATERNITY', 'Congé Paternité'), ('PARENTAL', 'Congé Parental'), ('BEREAVEMENT', 'Congé de Décès'), ('MARRIAGE', 'Congé de Mariage'), ('STUDY', 'Congé de Formation'), ('ADOPTION', "Congé d'Adoption"), ('ABSENCE', 'Absence')], default='ABSENCE', max_length=50),
        ),
    ]
