# Generated by Django 3.2.22 on 2024-06-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_alter_employeeabsence_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeabsence',
            name='message',
            field=models.TextField(default='', null=True),
        ),
    ]
