# Generated by Django 3.2.22 on 2024-11-05 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0030_alter_company_status'),
        ('human_ressources', '0057_employeecontractreplacedemployee_position'),
        ('planning', '0011_employeeabsence_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('starting_date_time', models.DateTimeField(null=True)),
                ('ending_date_time', models.DateTimeField(null=True)),
                ('scheduled_date_time', models.DateTimeField(null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.TextField(blank=True, null=True)),
                ('shift_type', models.CharField(choices=[('MORNING', 'Matin'), ('AFTERNOON', 'Après-midi'), ('NIGHT', 'Nuit')], default='MORNING', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'En Attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='APPROVED', max_length=50)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_shifts', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_shifts', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_shifts', to='human_ressources.employee')),
                ('employee_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_shifts', to='human_ressources.employeegroup')),
            ],
        ),
    ]
