# Generated by Django 3.2.22 on 2025-04-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_auto_20241105_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsence',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
