# Generated by Django 3.2.22 on 2025-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_auto_20250422_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsence',
            name='leave_type',
            field=models.CharField(choices=[('PAID', 'Congés payés (CP)'), ('UNPAID', 'Congé Sans Solde'), ('RWT', 'Temps de Travail Réduit (RTT)'), ('TEMPORARY', 'Congé Trimestriel (CT)'), ('ANNUAL', 'Congé Annuel'), ('SICK', 'Congé Maladie'), ('MATERNITY', 'Congé Maternité'), ('PATERNITY', 'Congé Paternité'), ('PARENTAL', 'Congé Parental'), ('BEREAVEMENT', 'Congé de Décès'), ('MARRIAGE', 'Congé de Mariage'), ('STUDY', 'Congé de Formation'), ('ADOPTION', "Congé d'Adoption"), ('SABBATICAL', 'Congé Sabbatique'), ('CAREGIVER', 'Congé de Proche Aidant'), ('FAMILY_SOLIDARITY', 'Congé de Solidarité Familiale'), ('MOBILITY', 'Congé de Mobilité'), ('RECONVERSION', 'Congé de Reconversion'), ('BUSINESS_CREATION', 'Congé pour Création ou Reprise d’Entreprise'), ('MANDATE', 'Congé pour Exercice de Mandat'), ('CHILD_SICKNESS', 'Congé pour Enfant Malade'), ('CHILD_BEREAVEMENT', 'Congé pour Deuil d’un Enfant'), ('ABSENCE', 'Absence absence Injustifiée'), ('SICK_LEAVE', 'Arrêt Maladie'), ('WORK_ACCIDENT', 'Accident du Travail'), ('PROFESSIONAL_ILLNESS', 'Maladie Professionnelle'), ('LONG_TERM_LEAVE', 'Arrêt Longue Durée'), ('CHILDCARE_LEAVE', 'Garde d’Enfant Malade'), ('FAMILY_REASON', 'Absence pour Motif Familial'), ('UNPAID_AUTHORIZED', 'Absence Autorisée Sans Solde'), ('LATE', 'Retard Non Justifié'), ('EXCEPTIONAL', 'Absence Exceptionnelle'), ('RELIGIOUS_HOLIDAY', 'Jour Férié Religieux (Non Chômé)'), ('TRAINING_INTERRUPTION', 'Interruption de Formation'), ('CONTRACT_SUSPENSION', 'Suspension du Contrat (hors maladie)'), ('OTHER', 'Autre')], default='ABSENCE', max_length=50),
        ),
    ]
