# Generated by Django 3.2.22 on 2025-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_alter_employeeabsence_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsence',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de traitement'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('NOT_JUSTIFIED', 'Non Justifié'), ('TO_JUSTIFY', 'À Justifier'), ('JUSTIFIED', 'Justifié')], default='PENDING', max_length=50),
        ),
    ]
