# Generated by Django 3.2.22 on 2023-12-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0006_auto_20231207_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_longitude',
        ),
    ]
