# Generated by Django 3.2.22 on 2024-02-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0009_alter_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
