# Generated by Django 3.2.22 on 2024-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0014_auto_20240313_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbeneficiary',
            name='beneficiaries',
            field=models.ManyToManyField(related_name='beneficiary_groups', to='human_ressources.Beneficiary'),
        ),
    ]
