# Generated by Django 3.2.22 on 2024-03-13 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_establishment_establishment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0010_auto_20240201_1012'),
        ('human_ressources', '0015_alter_groupbeneficiary_beneficiaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='', null=True)),
                ('observation', models.TextField(default='', null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_employee_company', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_employee_former', to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(related_name='employee_groups', to='human_ressources.Employee')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_employee_image', to='medias.file')),
            ],
        ),
    ]
