# Generated by Django 3.2.22 on 2024-03-13 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0016_groupemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEmployeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_employee_item_former', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_items', to='human_ressources.employee')),
                ('group_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_employee_items', to='human_ressources.groupemployee')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBeneficiaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_items', to='human_ressources.beneficiary')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_beneficiary_item_former', to=settings.AUTH_USER_MODEL)),
                ('group_beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_beneficiary_items', to='human_ressources.groupbeneficiary')),
            ],
        ),
        migrations.AlterField(
            model_name='groupbeneficiary',
            name='beneficiaries',
            field=models.ManyToManyField(related_name='beneficiary_groups', to='human_ressources.GroupBeneficiaryItem'),
        ),
    ]
