# Generated by Django 3.2.22 on 2024-03-13 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0009_establishment_establishment_type'),
        ('medias', '0010_auto_20240201_1012'),
        ('human_ressources', '0017_auto_20240313_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='', null=True)),
                ('observation', models.TextField(default='', null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_items', to='human_ressources.beneficiary')),
                ('beneficiary_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_group_items', to='human_ressources.beneficiarygroup')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_group_item_former', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='', null=True)),
                ('observation', models.TextField(default='', null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_group_company', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_group_former', to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(related_name='employee_groups', to='human_ressources.Employee')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_group_image', to='medias.file')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_group_item_former', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_items', to='human_ressources.employee')),
                ('employee_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_group_items', to='human_ressources.employeegroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupbeneficiaryitem',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='groupbeneficiaryitem',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='groupbeneficiaryitem',
            name='group_beneficiary',
        ),
        migrations.RemoveField(
            model_name='groupemployee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='groupemployee',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='groupemployee',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='groupemployee',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='groupemployee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='groupemployeeitem',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='groupemployeeitem',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='groupemployeeitem',
            name='group_employee',
        ),
        migrations.DeleteModel(
            name='GroupBeneficiary',
        ),
        migrations.DeleteModel(
            name='GroupBeneficiaryItem',
        ),
        migrations.DeleteModel(
            name='GroupEmployee',
        ),
        migrations.DeleteModel(
            name='GroupEmployeeItem',
        ),
        migrations.AddField(
            model_name='beneficiarygroup',
            name='beneficiaries',
            field=models.ManyToManyField(related_name='beneficiary_groups', to='human_ressources.BeneficiaryGroupItem'),
        ),
        migrations.AddField(
            model_name='beneficiarygroup',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_group_company', to='companies.company'),
        ),
        migrations.AddField(
            model_name='beneficiarygroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_group_former', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiarygroup',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder'),
        ),
        migrations.AddField(
            model_name='beneficiarygroup',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_group_image', to='medias.file'),
        ),
    ]
