# Generated by Django 3.2.22 on 2024-03-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0019_remove_beneficiarygroup_beneficiaries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeegroup',
            name='employees',
        ),
    ]
