# Generated by Django 3.2.22 on 2024-05-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0014_humangender'),
        ('human_ressources', '0021_employeecontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='admission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.humangender'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='preferred_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
