# Generated by Django 3.2.22 on 2024-05-03 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0018_establishment_establishment_category'),
        ('human_ressources', '0022_auto_20240502_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('release_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_ressources.beneficiary')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('establishments', models.ManyToManyField(related_name='establishments_beneficiary_entries', to='companies.Establishment')),
                ('internal_referents', models.ManyToManyField(related_name='referents_beneficiary_entries', to='human_ressources.Employee')),
            ],
        ),
    ]
