# Generated by Django 3.2.22 on 2024-05-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_establishment_establishment_category'),
        ('medias', '0010_auto_20240201_1012'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0023_beneficiaryentryitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeneficiaryEntryItem',
            new_name='BeneficiaryEntry',
        ),
        migrations.CreateModel(
            name='BeneficiaryAdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField(null=True)),
                ('ending_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_ressources.beneficiary')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_documents', to='medias.file')),
            ],
        ),
    ]
