# Generated by Django 3.2.22 on 2024-05-03 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0010_auto_20240201_1012'),
        ('data_management', '0015_admissiondocumenttype'),
        ('human_ressources', '0024_auto_20240503_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryadmissiondocument',
            name='admission_document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.admissiondocumenttype'),
        ),
        migrations.AlterField(
            model_name='beneficiaryadmissiondocument',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_admission_documents', to='medias.file'),
        ),
    ]
