# Generated by Django 3.2.22 on 2024-05-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0006_financier'),
        ('human_ressources', '0025_auto_20240503_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryadmissiondocument',
            name='financier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.financier'),
        ),
    ]
