# Generated by Django 3.2.22 on 2024-05-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0010_auto_20240201_1012'),
        ('human_ressources', '0026_beneficiaryadmissiondocument_financier'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_contrat_doucument', to='medias.file'),
        ),
    ]
