# Generated by Django 3.2.22 on 2024-05-20 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_establishment_company'),
        ('human_ressources', '0028_auto_20240520_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_employee_contracts', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_beneficiaries', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='beneficiarygroup',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_beneficiary_groups', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_employees', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='employeegroup',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_employee_groups', to='companies.company'),
        ),
    ]
