# Generated by Django 3.2.22 on 2024-05-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0019_employeecontracttype'),
        ('human_ressources', '0029_auto_20240520_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecontract',
            old_name='finished_at',
            new_name='ended_at',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='company',
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='contrat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.employeecontracttype'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
