# Generated by Django 3.2.22 on 2024-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0030_auto_20240521_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
