# Generated by Django 3.2.22 on 2024-05-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0031_employeecontract_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='observation',
            field=models.TextField(default='', null=True),
        ),
    ]
