# Generated by Django 3.2.22 on 2024-05-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0033_auto_20240521_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecontract',
            old_name='contrat_type',
            new_name='contract_type',
        ),
    ]
