# Generated by Django 3.2.22 on 2024-05-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0034_rename_contrat_type_employeecontract_contract_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecontract',
            old_name='name',
            new_name='title',
        ),
    ]
