# Generated by Django 3.2.22 on 2024-05-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0035_rename_name_employeecontract_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
