# Generated by Django 3.2.22 on 2024-05-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0011_file_company'),
        ('human_ressources', '0037_employeecontract_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryadmissiondocument',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_admission_documents', to='human_ressources.beneficiary'),
        ),
        migrations.AlterField(
            model_name='beneficiaryadmissiondocument',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_beneficiary_admission_documents', to='medias.file'),
        ),
        migrations.AlterField(
            model_name='beneficiaryentry',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_entries', to='human_ressources.beneficiary'),
        ),
    ]
