# Generated by Django 3.2.22 on 2024-06-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0040_employeecontractestablishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='contract_type',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD')], default='CDI', max_length=50, null=True),
        ),
    ]
