# Generated by Django 3.2.22 on 2024-06-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0042_alter_employeecontract_contract_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecontract',
            name='annual_leave_days',
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='initial_annual_leave_days',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Initial Annual Leave Days (CP)'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='initial_ct_days',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Initial Temporary Leave Days (CT)'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='initial_rtt_days',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Initial RTT Days'),
        ),
    ]
