# Generated by Django 3.2.22 on 2024-06-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0043_auto_20240624_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='monthly_gross_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Gross Salary'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional if Monthly Gross Salary is provided', max_digits=10, null=True, verbose_name='Annual Gross Salary'),
        ),
    ]
