# Generated by Django 3.2.22 on 2024-06-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0044_auto_20240625_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecontract',
            old_name='initial_rtt_days',
            new_name='initial_rwt_days',
        ),
    ]
