# Generated by Django 3.2.22 on 2024-06-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0045_rename_initial_rtt_days_employeecontract_initial_rwt_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecontract',
            old_name='initial_annual_leave_days',
            new_name='initial_paid_leave_days',
        ),
        migrations.RenameField(
            model_name='employeecontract',
            old_name='initial_ct_days',
            new_name='initial_temporary_days',
        ),
    ]
