# Generated by Django 3.2.22 on 2024-07-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0046_auto_20240626_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
