# Generated by Django 3.2.22 on 2024-07-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0048_auto_20240715_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='registration_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
