# Generated by Django 3.2.22 on 2024-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0049_employee_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='contract_type',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('APPRENTICESHIP_CONTRACT', "Contrat d'apprentissage"), ('SINGLE_INTEGRATION_CONTRACT', "Contrat Unique d'Insertion (CUI)")], default='CDI', max_length=50),
        ),
    ]
