# Generated by Django 3.2.22 on 2024-10-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0051_alter_employeecontract_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
