# Generated by Django 3.2.22 on 2024-10-28 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0033_employeemission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0053_alter_employeecontract_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContractMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_contract_mission_former', to=settings.AUTH_USER_MODEL)),
                ('employee_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='human_ressources.employeecontract')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_contract_missions', to='data_management.employeemission')),
            ],
        ),
    ]
