# Generated by Django 3.2.22 on 2024-10-28 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0054_employeecontractmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContractReplacedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField(null=True)),
                ('ending_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_contract_eeplaced_employee_former', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_contract_eeplaced_employee', to='human_ressources.employee')),
                ('employee_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_employees', to='human_ressources.employeecontract')),
            ],
        ),
    ]
