# Generated by Django 3.2.22 on 2024-11-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0055_employeecontractreplacedemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontractreplacedemployee',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
