# Generated by Django 3.2.22 on 2024-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0057_employeecontractreplacedemployee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='additional_address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='additional_address',
            field=models.TextField(default='', null=True),
        ),
    ]
