# Generated by Django 3.2.22 on 2024-12-13 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0041_beneficiarystatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0013_contracttemplate_image'),
        ('human_ressources', '0058_auto_20241212_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryStatusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField(null=True)),
                ('ending_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_status_entries', to='human_ressources.beneficiary')),
                ('beneficiary_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.beneficiarystatus')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_status_entries', to='medias.file')),
            ],
        ),
    ]
