# Generated by Django 3.2.22 on 2024-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0059_beneficiarystatusentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryentry',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
