# Generated by Django 3.2.22 on 2024-12-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0035_companymedia_blog_url'),
        ('human_ressources', '0061_beneficiaryadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryadmission',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_admissions', to='human_ressources.employee'),
        ),
        migrations.AddField(
            model_name='beneficiaryadmission',
            name='establishments',
            field=models.ManyToManyField(related_name='beneficiary_admissions', to='companies.Establishment'),
        ),
    ]
