# Generated by Django 3.2.22 on 2024-12-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0013_contracttemplate_image'),
        ('human_ressources', '0062_auto_20241227_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryadmission',
            name='files',
            field=models.ManyToManyField(related_name='file_beneficiary_admissions', to='medias.File'),
        ),
    ]
