# Generated by Django 3.2.22 on 2025-01-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0065_employee_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryadmission',
            name='reception_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryadmission',
            name='response_date',
            field=models.DateTimeField(null=True),
        ),
    ]
