# Generated by Django 3.2.22 on 2025-01-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0066_auto_20250117_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='birth_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='birth_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='birth_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryadmission',
            name='birth_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryadmission',
            name='birth_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryadmission',
            name='birth_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryadmission',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
