# Generated by Django 3.2.22 on 2025-01-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0069_auto_20250122_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Homme'), ('FEMALE', 'Femme'), ('NOT_SPECIFIED', 'Non spécifié')], default='NOT_SPECIFIED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryadmission',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Homme'), ('FEMALE', 'Femme'), ('NOT_SPECIFIED', 'Non spécifié')], default='NOT_SPECIFIED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Homme'), ('FEMALE', 'Femme'), ('NOT_SPECIFIED', 'Non spécifié')], default='NOT_SPECIFIED', max_length=50, null=True),
        ),
    ]
