# Generated by Django 3.2.22 on 2025-01-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0046_professionalstatus_typeendowment'),
        ('human_ressources', '0070_auto_20250122_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='professional_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='data_management.professionalstatus'),
        ),
        migrations.AddField(
            model_name='beneficiaryadmission',
            name='professional_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_admissions', to='data_management.professionalstatus'),
        ),
    ]
