# Generated by Django 3.2.22 on 2025-01-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0071_auto_20250123_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='beneficiaryadmission',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='email'),
        ),
    ]
