# Generated by Django 3.2.22 on 2025-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0072_auto_20250130_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='email'),
        ),
    ]
