# Generated by Django 3.2.22 on 2025-01-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0074_addressbookentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbookentry',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_book_entries', to='human_ressources.beneficiary'),
        ),
    ]
