# Generated by Django 3.2.22 on 2025-01-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0075_addressbookentry_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbookentry',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
