# Generated by Django 3.2.22 on 2025-01-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0076_addressbookentry_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressBookEntry',
        ),
    ]
