# Generated by Django 3.2.22 on 2025-01-31 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0035_companymedia_blog_url'),
        ('data_management', '0047_addressbookentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0077_delete_addressbookentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('career_type', models.CharField(choices=[('EDUCATION', 'Scolarité'), ('INTERNSHIP', 'Stage'), ('JOB', 'Emploi'), ('TRAINING', 'Formation'), ('VOLUNTEERING', 'Bénévolat'), ('OTHER', 'Autre')], default='EDUCATION', max_length=20)),
                ('institution', models.CharField(max_length=255, null=True)),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('starting_date', models.DateField(null=True)),
                ('ending_date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='email')),
                ('full_address', models.TextField(default='', null=True)),
                ('address', models.TextField(default='', null=True)),
                ('additional_address', models.TextField(default='', null=True)),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('mobile', models.CharField(max_length=255, null=True)),
                ('fix', models.CharField(max_length=255, null=True)),
                ('fax', models.CharField(max_length=255, null=True)),
                ('web_site', models.URLField(max_length=255, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('other_contacts', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_entries', to='human_ressources.beneficiary')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_entries', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='former_career_entries', to=settings.AUTH_USER_MODEL)),
                ('professional_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_entries', to='data_management.professionalstatus')),
            ],
        ),
    ]
