# Generated by Django 3.2.22 on 2025-01-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0078_careerentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerentry',
            old_name='job_title',
            new_name='title',
        ),
    ]
