# Generated by Django 3.2.22 on 2025-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0079_rename_job_title_careerentry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryadmission',
            name='pre_admission_date',
            field=models.DateTimeField(null=True),
        ),
    ]
