# Generated by Django 3.2.22 on 2025-02-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0080_beneficiaryadmission_pre_admission_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiaryentry',
            options={'ordering': ['entry_date']},
        ),
    ]
