# Generated by Django 3.2.22 on 2025-03-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0083_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
