# Generated by Django 3.2.22 on 2025-04-08 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0021_alter_jobcandidateinformationsheet_status'),
        ('human_ressources', '0084_alter_advance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='recruitment.jobcandidate'),
        ),
    ]
