# Generated by Django 3.2.22 on 2025-04-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_auto_20250422_1105'),
        ('human_ressources', '0085_employee_job_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='establishments',
            field=models.ManyToManyField(related_name='employees', to='companies.Establishment'),
        ),
    ]
