# Generated by Django 3.2.22 on 2025-05-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0086_employee_establishments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryadmissiondocument',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_admission_documents', to='human_ressources.beneficiary'),
        ),
        migrations.AlterField(
            model_name='beneficiaryendowmententry',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_endowment_entries', to='human_ressources.beneficiary'),
        ),
        migrations.AlterField(
            model_name='beneficiaryentry',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_entries', to='human_ressources.beneficiary'),
        ),
        migrations.AlterField(
            model_name='beneficiarystatusentry',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_status_entries', to='human_ressources.beneficiary'),
        ),
        migrations.AlterField(
            model_name='careerentry',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_entries', to='human_ressources.beneficiary'),
        ),
    ]
