# Generated by Django 3.2.22 on 2025-05-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0087_auto_20250512_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='human_ressources.employee'),
        ),
    ]
