# Generated by Django 3.2.22 on 2025-05-19 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0089_alter_employee_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGroupManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_group_manager_former', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_group_manager', to='human_ressources.employee')),
                ('employee_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='human_ressources.employeegroup')),
            ],
        ),
    ]
