# Generated by Django 3.2.22 on 2025-05-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0090_employeegroupmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroup',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
