# Generated by Django 3.2.22 on 2023-10-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('upload_to', models.CharField(max_length=255, null=True)),
                ('file_type', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(null=True, upload_to=medias.models.file_directory_path)),
                ('video', models.FileField(null=True, upload_to=medias.models.file_directory_path)),
                ('image', models.ImageField(null=True, upload_to=medias.models.file_directory_path)),
                ('is_active', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
