# Generated by Django 3.2.22 on 2023-11-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='caption',
            field=models.TextField(default='', null=True),
        ),
    ]
