# Generated by Django 3.2.22 on 2023-11-22 09:27

from django.db import migrations, models
import medias.models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_file_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=medias.models.file_directory_path),
        ),
    ]
