# Generated by Django 3.2.22 on 2023-11-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_file_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at']},
        ),
    ]
