# Generated by Django 3.2.22 on 2023-12-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0005_auto_20231213_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='descreption',
            new_name='description',
        ),
    ]
