# Generated by Django 3.2.22 on 2024-01-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0008_alter_folder_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
