# Generated by Django 3.2.22 on 2024-10-04 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_company_sce_shop_url'),
        ('human_ressources', '0051_alter_employeecontract_contract_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0011_file_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(default='', null=True)),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('APPRENTICESHIP_CONTRACT', "Contrat d'apprentissage"), ('SINGLE_INTEGRATION_CONTRACT', "Contrat Unique d'Insertion (CUI)"), ('PROFESSIONALIZATION_CONTRACT', 'Contrat de professionnalisation'), ('SEASONAL_CONTRACT', 'Contrat saisonnier'), ('TEMPORARY_CONTRACT', 'Contrat intérimaire'), ('PART_TIME_CONTRACT', 'Contrat à temps partiel'), ('FULL_TIME_CONTRACT', 'Contrat à temps plein'), ('INTERNSHIP_CONTRACT', 'Contrat de stage')], default='CDI', max_length=50)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates_former', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates', to='human_ressources.employee')),
            ],
        ),
    ]
