# Generated by Django 3.2.22 on 2025-01-31 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0047_addressbookentry'),
        ('human_ressources', '0079_rename_job_title_careerentry_title'),
        ('companies', '0035_companymedia_blog_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0013_contracttemplate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('starting_date', models.DateField(null=True)),
                ('ending_date', models.DateField(null=True)),
                ('description', models.TextField(default='', null=True)),
                ('is_notification_enabled', models.BooleanField(default=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='human_ressources.beneficiary')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='medias.file')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='data_management.documenttype')),
            ],
        ),
    ]
