# Generated by Django 3.2.22 on 2025-02-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0048_beneficiarydocumenttype'),
        ('medias', '0014_documentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='beneficiary_document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='data_management.beneficiarydocumenttype'),
        ),
    ]
