# Generated by Django 3.2.22 on 2025-02-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0016_auto_20250227_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentrecord',
            old_name='measurement_activity_unit',
            new_name='notification_period_unit',
        ),
    ]
