# Generated by Django 3.2.22 on 2025-03-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0050_jobcandidatedocumenttype'),
        ('medias', '0017_rename_measurement_activity_unit_documentrecord_notification_period_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='job_candidate_document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='data_management.jobcandidatedocumenttype'),
        ),
    ]
