# Generated by Django 3.2.22 on 2025-03-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_auto_20250317_1003'),
        ('medias', '0018_documentrecord_job_candidate_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='job_candidate_information_sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='recruitment.jobcandidateinformationsheet'),
        ),
    ]
