# Generated by Django 3.2.22 on 2025-03-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0019_documentrecord_job_candidate_information_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='comment',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='observation',
            field=models.TextField(default='', null=True),
        ),
    ]
