# Generated by Django 3.2.22 on 2025-05-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0021_alter_jobcandidateinformationsheet_status'),
        ('human_ressources', '0087_auto_20250512_1655'),
        ('medias', '0020_auto_20250321_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrecord',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_records', to='human_ressources.beneficiary'),
        ),
        migrations.AlterField(
            model_name='documentrecord',
            name='job_candidate_information_sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_records', to='recruitment.jobcandidateinformationsheet'),
        ),
    ]
