# Generated by Django 3.2.22 on 2023-10-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('name', models.CharField(default='Entreprise sans nom', max_length=255)),
                ('primary_color', models.TextField(default='#ffffff', null=True)),
                ('secondary_color', models.TextField(default='#cccccc', null=True)),
                ('text_color', models.TextField(default='#333333', null=True)),
                ('opening_date', models.DateTimeField(null=True)),
                ('closing_date', models.DateTimeField(null=True)),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=25, null=True)),
                ('mobile', models.CharField(max_length=255, null=True)),
                ('fix', models.CharField(max_length=255, null=True)),
                ('fax', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('authorized_domains', models.TextField(default='', null=True)),
                ('web_site', models.URLField(max_length=255, null=True)),
                ('other_contacts', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('observation', models.TextField(default='', null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cover_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compnay_cover_image', to='medias.file')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compnay_creator', to=settings.AUTH_USER_MODEL)),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compnay_logo', to='medias.file')),
            ],
        ),
    ]
