# Generated by Django 3.2.22 on 2024-02-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
