# Generated by Django 3.2.22 on 2024-03-11 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0010_auto_20240201_1012'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0007_alter_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_cover_image', to='medias.file'),
        ),
        migrations.AlterField(
            model_name='company',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logo', to='medias.file'),
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('name', models.CharField(default='Entreprise sans nom', max_length=255)),
                ('siret', models.CharField(max_length=255, null=True)),
                ('primary_color', models.TextField(default='#ffffff', null=True)),
                ('secondary_color', models.TextField(default='#cccccc', null=True)),
                ('text_color', models.TextField(default='#333333', null=True)),
                ('opening_date', models.DateTimeField(null=True)),
                ('closing_date', models.DateTimeField(null=True)),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(default='', null=True)),
                ('mobile', models.CharField(max_length=255, null=True)),
                ('fix', models.CharField(max_length=255, null=True)),
                ('fax', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('web_site', models.URLField(max_length=255, null=True)),
                ('other_contacts', models.CharField(max_length=255, null=True)),
                ('iban', models.CharField(max_length=255, null=True)),
                ('bic', models.CharField(max_length=255, null=True)),
                ('bank_name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('observation', models.TextField(default='', null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cover_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_cover_image', to='medias.file')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_creator', to=settings.AUTH_USER_MODEL)),
                ('establishment_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_childs', to='companies.establishment')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder')),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_logo', to='medias.file')),
            ],
        ),
    ]
