# Generated by Django 3.2.22 on 2024-04-05 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0010_auto_20240201_1012'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0009_establishment_establishment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(default='Etablissement sans nom', max_length=255),
        ),
        migrations.CreateModel(
            name='EstablishmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('name', models.CharField(default='Service sans nom', max_length=255)),
                ('description', models.TextField(default='', null=True)),
                ('observation', models.TextField(default='', null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_creator', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_services', to='companies.establishment')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_service_image', to='medias.file')),
            ],
        ),
    ]
