# Generated by Django 3.2.22 on 2024-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20240405_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishmentservice',
            name='siret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
