# Generated by Django 3.2.22 on 2024-04-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0012_establishmenttype'),
        ('companies', '0012_establishmentservice_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='establishment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.establishmenttype'),
        ),
    ]
