# Generated by Django 3.2.22 on 2024-05-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_delete_establishmentservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='ape_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='finess',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
