# Generated by Django 3.2.22 on 2024-05-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0013_establishmentcategory'),
        ('companies', '0017_establishmentmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='establishment_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.establishmentcategory'),
        ),
    ]
