# Generated by Django 3.2.22 on 2024-05-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_establishment_establishment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
