# Generated by Django 3.2.22 on 2024-05-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_establishment_measurement_activity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityauthorization',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.establishment'),
        ),
    ]
