# Generated by Django 3.2.22 on 2024-05-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0011_file_company'),
        ('companies', '0023_alter_activityauthorization_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityauthorization',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_authorization_file', to='medias.file'),
        ),
    ]
