# Generated by Django 3.2.22 on 2024-10-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'En attente de vérification'), ('SUSPENDED', 'Suspendue'), ('CLOSED', 'Fermée'), ('TRIAL', "En période d'essai"), ('EXPIRED', 'Expiré'), ('RENEWAL_PENDING', 'Renouvellement en attente')], default='TRIAL', max_length=20),
        ),
    ]
