# Generated by Django 3.2.22 on 2024-11-21 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0013_contracttemplate_image'),
        ('companies', '0031_auto_20241121_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='collective_agreement',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_agreement',
        ),
        migrations.CreateModel(
            name='CompanyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sce_shop_url', models.URLField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('collective_agreement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collective_agreement_company_medias', to='medias.file')),
                ('company_agreement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_agreement_company_medias', to='medias.file')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_medias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companymedia'),
        ),
    ]
