# Generated by Django 3.2.22 on 2024-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_auto_20241125_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='additional_address',
            field=models.TextField(default='', null=True),
        ),
    ]
