# Generated by Django 3.2.22 on 2024-12-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_company_additional_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymedia',
            name='blog_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
