# Generated by Django 3.2.22 on 2025-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_alter_establishment_measurement_activity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymedia',
            name='associations_foundations_code_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companymedia',
            name='collective_agreement_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companymedia',
            name='company_agreement_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companymedia',
            name='labor_law_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companymedia',
            name='safc_code_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
