# Generated by Django 3.2.22 on 2025-04-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0038_company_hidden_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='account_number',
            field=models.CharField(max_length=11, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='bank_code',
            field=models.CharField(max_length=5, null=True, verbose_name='Bank Code'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='branch_code',
            field=models.CharField(max_length=5, null=True, verbose_name='Branch Code'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='rib_key',
            field=models.CharField(max_length=2, null=True, verbose_name='RIB Key'),
        ),
    ]
