# Generated by Django 3.2.22 on 2025-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0040_auto_20250422_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ape_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='finess',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='siret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
