# Generated by Django 3.2.22 on 2025-04-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_auto_20250422_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approval_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
