# Generated by Django 3.2.22 on 2024-12-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancemember',
            name='additional_address',
            field=models.TextField(default='', null=True),
        ),
    ]
