# Generated by Django 3.2.22 on 2025-05-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_governancemember_additional_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancemember',
            name='is_archived',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
