# Generated by Django 3.2.22 on 2025-05-26 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('governance', '0003_governancemember_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancemember',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'Président'), ('TREASURER', 'Trésorier'), ('ASSISTANT_TREASURER', 'Trésorier Adjoint'), ('SECRETARY', 'Secrétaire'), ('ASSISTANT_SECRETARY', 'Secrétaire Adjoint'), ('MEMBER', 'Membre')], default='MEMBER', max_length=50),
        ),
        migrations.CreateModel(
            name='GovernanceMemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRESIDENT', 'Président'), ('TREASURER', 'Trésorier'), ('ASSISTANT_TREASURER', 'Trésorier Adjoint'), ('SECRETARY', 'Secrétaire'), ('ASSISTANT_SECRETARY', 'Secrétaire Adjoint'), ('MEMBER', 'Membre')], default='MEMBER', max_length=50)),
                ('starting_date_time', models.DateTimeField(null=True)),
                ('ending_date_time', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_member_roles', to=settings.AUTH_USER_MODEL)),
                ('governance_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_member_roles', to='governance.governancemember')),
            ],
        ),
    ]
