# Generated by Django 3.2.22 on 2025-05-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_auto_20250526_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancememberrole',
            name='other_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='governancemember',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'Président'), ('TREASURER', 'Trésorier'), ('ASSISTANT_TREASURER', 'Trésorier Adjoint'), ('SECRETARY', 'Secrétaire'), ('ASSISTANT_SECRETARY', 'Secrétaire Adjoint'), ('MEMBER', 'Membre'), ('OTHER', 'Autre')], default='MEMBER', max_length=50),
        ),
        migrations.AlterField(
            model_name='governancememberrole',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'Président'), ('TREASURER', 'Trésorier'), ('ASSISTANT_TREASURER', 'Trésorier Adjoint'), ('SECRETARY', 'Secrétaire'), ('ASSISTANT_SECRETARY', 'Secrétaire Adjoint'), ('MEMBER', 'Membre'), ('OTHER', 'Autre')], default='MEMBER', max_length=50),
        ),
    ]
