# Generated by Django 3.2.22 on 2025-05-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_auto_20250526_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governancemember',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
