# Generated by Django 3.2.22 on 2025-06-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_alter_governancemember_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governancememberrole',
            options={'ordering': ['starting_date_time']},
        ),
    ]
