# Generated by Django 3.2.22 on 2024-03-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0020_remove_employeegroup_employees'),
        ('qualities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndesirableEventBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_beneficiary', to='human_ressources.beneficiary')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_beneficiary_former', to=settings.AUTH_USER_MODEL)),
                ('undesirable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualities.undesirableevent')),
            ],
        ),
    ]
