# Generated by Django 3.2.22 on 2024-03-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0020_remove_employeegroup_employees'),
        ('qualities', '0002_undesirableeventbeneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='undesirableevent',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_undesirable_events', to='human_ressources.employee'),
        ),
    ]
