# Generated by Django 3.2.22 on 2024-03-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0004_rename_undesirable_undesirableeventbeneficiary_undesirable_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='undesirableevent',
            name='undesirable_event_type',
            field=models.CharField(choices=[('NORMAL', 'EVENEMENT INDESIRABLE (EI) - Normal'), ('SERIOUS', 'EVENEMENT INDESIRABLE GRAVE (EIG) - Grave')], default='NORMAL', max_length=50, null=True),
        ),
    ]
