# Generated by Django 3.2.22 on 2024-03-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_undesirableeventfrequency'),
        ('qualities', '0008_auto_20240318_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undesirableevent',
            name='undesirable_event_normal_types',
        ),
        migrations.RemoveField(
            model_name='undesirableevent',
            name='undesirable_event_serious_types',
        ),
        migrations.AddField(
            model_name='undesirableevent',
            name='normal_types',
            field=models.ManyToManyField(related_name='normal_type_undesirable_events', to='data_management.UndesirableEventNormalType'),
        ),
        migrations.AddField(
            model_name='undesirableevent',
            name='serious_types',
            field=models.ManyToManyField(related_name='serious_type_undesirable_events', to='data_management.UndesirableEventSeriousType'),
        ),
    ]
