# Generated by Django 3.2.22 on 2024-03-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0010_undesirableevent_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='undesirableevent',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('SEVERE', 'Grave'), ('VERY_SERIOUS', 'Très grave')], default='MEDIUM', max_length=50, null=True),
        ),
    ]
