# Generated by Django 3.2.22 on 2024-03-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0012_undesirableevent_persons_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undesirableevent',
            name='persons_notified',
        ),
    ]
