# Generated by Django 3.2.22 on 2024-03-18 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0020_remove_employeegroup_employees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualities', '0014_undesirableeventpersonnotified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UndesirableEventPersonNotified',
            new_name='UndesirableEventNotifiedPerson',
        ),
    ]
