# Generated by Django 3.2.22 on 2024-03-18 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0020_remove_employeegroup_employees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualities', '0015_rename_undesirableeventpersonnotified_undesirableeventnotifiedperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undesirableeventnotifiedperson',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_notified_person_former', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='undesirableeventnotifiedperson',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_notified_person', to='human_ressources.employee'),
        ),
    ]
