# Generated by Django 3.2.22 on 2024-03-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0016_auto_20240318_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='undesirableevent',
            name='other_notified_persons',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='undesirableevent',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
