# Generated by Django 3.2.22 on 2024-03-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0017_auto_20240318_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='undesirableevent',
            name='actions_taken_text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='undesirableevent',
            name='circumstance_event_text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='undesirableevent',
            name='course_facts_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='undesirableevent',
            name='course_facts_place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
