# Generated by Django 3.2.22 on 2024-04-05 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20240405_1042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualities', '0019_undesirableeventestablishment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndesirableEventEstablishmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_establishment_service_former', to=settings.AUTH_USER_MODEL)),
                ('establishment_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_establishment_service', to='companies.establishmentservice')),
                ('undesirable_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualities.undesirableevent')),
            ],
        ),
    ]
