# Generated by Django 3.2.22 on 2024-06-07 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20240530_1515'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0011_file_company'),
        ('human_ressources', '0038_auto_20240530_1526'),
        ('qualities', '0025_undesirableevent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undesirableeventbeneficiary',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_beneficiaries', to='human_ressources.beneficiary'),
        ),
        migrations.AlterField(
            model_name='undesirableeventbeneficiary',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_beneficiaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='undesirableeventemployee',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='undesirableeventemployee',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_employees', to='human_ressources.employee'),
        ),
        migrations.AlterField(
            model_name='undesirableeventestablishment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_establishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='undesirableeventestablishment',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_establishments', to='companies.establishment'),
        ),
        migrations.AlterField(
            model_name='undesirableeventnotifiedperson',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_notified_persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='undesirableeventnotifiedperson',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_notified_persons', to='human_ressources.employee'),
        ),
        migrations.CreateModel(
            name='UndesirableEventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField(default='', null=True)),
                ('description', models.TextField(default='', null=True)),
                ('observation', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_reviews', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_reviews', to='medias.file')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder')),
                ('undesirable_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualities.undesirableevent')),
            ],
        ),
    ]
