# Generated by Django 3.2.22 on 2024-06-07 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0038_auto_20240530_1526'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualities', '0026_auto_20240607_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undesirableeventreview',
            name='description',
        ),
        migrations.RemoveField(
            model_name='undesirableeventreview',
            name='document',
        ),
        migrations.RemoveField(
            model_name='undesirableeventreview',
            name='observation',
        ),
        migrations.CreateModel(
            name='UndesirableEventAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(default='', null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_event_actions', to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(related_name='undesirable_event_actions', to='human_ressources.Employee')),
                ('undesirable_event_review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualities.undesirableeventreview')),
            ],
        ),
    ]
