# Generated by Django 3.2.22 on 2024-06-10 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0038_auto_20240530_1526'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0026_auto_20240530_1515'),
        ('medias', '0011_file_company'),
        ('qualities', '0029_auto_20240607_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlanObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute')], default='LOW', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'À traiter'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé'), ('STARTED', 'En cours'), ('FINISHED', 'Terminée'), ('PENDING', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='NEW', max_length=50)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plan_objectives', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plan_objectives', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plan_objectives', to='human_ressources.employee')),
                ('establishments', models.ManyToManyField(related_name='action_plan_objectives', to='companies.Establishment')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder')),
                ('undesirable_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='qualities.undesirableevent')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlanObjectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(default='', null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('NEW', 'À traiter'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé'), ('STARTED', 'En cours'), ('FINISHED', 'Terminée'), ('PENDING', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='NEW', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action_plan_objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='qualities.actionplanobjective')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plan_objective_actions', to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(related_name='action_plan_objective_actions', to='human_ressources.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='undesirableeventreview',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='undesirableeventreview',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='undesirableeventreview',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='undesirableeventreview',
            name='undesirable_event',
        ),
        migrations.DeleteModel(
            name='UndesirableEventAction',
        ),
        migrations.DeleteModel(
            name='UndesirableEventReview',
        ),
    ]
