# Generated by Django 3.2.22 on 2024-06-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0031_auto_20240610_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplanobjective',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('ON_HOLD', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='actionplanobjectiveaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('ON_HOLD', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='undesirableevent',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('ON_HOLD', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='NEW', max_length=50),
        ),
    ]
