# Generated by Django 3.2.22 on 2024-06-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0032_auto_20240611_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplanobjectiveaction',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'À traiter'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Traité')], default='NEW', max_length=50),
        ),
    ]
