# Generated by Django 3.2.22 on 2024-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0033_alter_actionplanobjectiveaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplanobjectiveaction',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'À traiter'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Traité')], default='TO_DO', max_length=50),
        ),
    ]
