# Generated by Django 3.2.22 on 2024-06-13 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0038_auto_20240530_1526'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualities', '0034_alter_actionplanobjectiveaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlanAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(default='', null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('TO_DO', 'À traiter'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Traité')], default='TO_DO', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action_plan_objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='qualities.actionplanobjective')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plan_actions', to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(related_name='action_plan_actions', to='human_ressources.Employee')),
            ],
        ),
        migrations.DeleteModel(
            name='ActionPlanObjectiveAction',
        ),
    ]
