# Generated by Django 3.2.22 on 2024-06-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0011_file_company'),
        ('qualities', '0036_auto_20240613_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplanaction',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plan_actions', to='medias.file'),
        ),
    ]
