# Generated by Django 3.2.22 on 2024-06-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0037_actionplanaction_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplanaction',
            name='number',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
