# Generated by Django 3.2.22 on 2024-06-17 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0011_file_company'),
        ('human_ressources', '0038_auto_20240530_1526'),
        ('companies', '0026_auto_20240530_1515'),
        ('qualities', '0039_auto_20240617_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=255, null=True)),
                ('action', models.TextField(default='', null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('TO_DO', 'À traiter'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Traité')], default='TO_DO', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_actions', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_actions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_actions', to='medias.file')),
                ('employees', models.ManyToManyField(related_name='task_actions', to='human_ressources.Employee')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='qualities.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='ActionPlanAction',
        ),
    ]
