# Generated by Django 3.2.22 on 2024-06-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0035_auto_20240624_1108'),
        ('qualities', '0042_alter_undesirableevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='undesirableevent',
            name='call',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undesirable_events', to='administratives.call'),
        ),
    ]
