# Generated by Django 3.2.22 on 2024-07-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0043_undesirableevent_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='undesirableevent',
            name='concerned_families',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='undesirableevent',
            name='other_notified_persons',
            field=models.TextField(default='', null=True),
        ),
    ]
