# Generated by Django 3.2.22 on 2024-07-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0044_auto_20240704_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='undesirableevent',
            name='other_types',
            field=models.TextField(default='', null=True),
        ),
    ]
