# Generated by Django 3.2.22 on 2024-07-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0045_undesirableevent_other_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undesirableevent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('NEW', 'Déclaré'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Traité'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé'), ('COMPLETED', 'Terminée'), ('ON_HOLD', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='DRAFT', max_length=50),
        ),
    ]
