# Generated by Django 3.2.22 on 2024-10-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0011_file_company'),
        ('qualities', '0046_alter_undesirableevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='undesirableevent',
            name='files',
            field=models.ManyToManyField(related_name='file_undesirable_events', to='medias.File'),
        ),
    ]
