# Generated by Django 3.2.22 on 2024-10-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0051_alter_employeecontract_contract_type'),
        ('qualities', '0047_undesirableevent_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='undesirableevent',
            name='declarants',
            field=models.ManyToManyField(related_name='declarants_undesirable_events', to='human_ressources.Employee'),
        ),
    ]
