# Generated by Django 3.2.22 on 2023-10-26 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('is_in_service', models.BooleanField(null=True)),
                ('is_out_of_order', models.BooleanField(null=True)),
                ('designation', models.TextField()),
                ('is_rented', models.BooleanField(null=True)),
                ('is_bought', models.BooleanField(null=True)),
                ('driver_name', models.TextField(null=True)),
                ('driver_number', models.TextField(null=True)),
                ('buying_price', models.FloatField(null=True)),
                ('rental_price', models.FloatField(null=True)),
                ('advance_paid', models.FloatField(null=True)),
                ('purchase_date', models.DateTimeField(null=True)),
                ('rental_date', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('observation', models.TextField()),
                ('is_active', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_driver', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_image', to='medias.file')),
            ],
        ),
    ]
