# Generated by Django 3.2.22 on 2023-10-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='designation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='observation',
            field=models.TextField(default='', null=True),
        ),
    ]
