# Generated by Django 3.2.22 on 2024-05-29 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_management', '0022_vehiclebrand_vehiclemodel'),
        ('human_ressources', '0037_employeecontract_folder'),
        ('companies', '0025_activityauthorization_temporary_capacity'),
        ('vehicles', '0007_vehicle_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='advance_paid',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_bought',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_in_service',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_out_of_order',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_rented',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rental_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rental_price',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.ManyToManyField(related_name='brand_vehicles', to='data_management.VehicleBrand'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ManyToManyField(related_name='model_vehicles', to='data_management.VehicleModel'),
        ),
        migrations.CreateModel(
            name='VehicleEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField(null=True)),
                ('ending_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('establishments', models.ManyToManyField(related_name='vehicle_establishments', to='companies.Establishment')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField(null=True)),
                ('ending_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(related_name='vehicle_employees', to='human_ressources.Employee')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
    ]
