# Generated by Django 3.2.22 on 2024-05-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0022_vehiclebrand_vehiclemodel'),
        ('vehicles', '0008_auto_20240529_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_brand',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_vehicles', to='data_management.vehiclebrand'),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_model',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_vehicles', to='data_management.vehiclemodel'),
        ),
    ]
