# Generated by Django 3.2.22 on 2024-05-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_auto_20240530_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleownership',
            old_name='end_date',
            new_name='ending_date',
        ),
        migrations.RenameField(
            model_name='vehicleownership',
            old_name='start_date',
            new_name='starting_date',
        ),
        migrations.RemoveField(
            model_name='vehicleownership',
            name='lease_duration_months',
        ),
        migrations.AlterField(
            model_name='vehicleownership',
            name='ownership_type',
            field=models.CharField(choices=[('LEASE', 'Location'), ('PURCHASE', 'Achat'), ('SALE', 'Vente')], default='LEASE', max_length=10, null=True),
        ),
    ]
