# Generated by Django 3.2.22 on 2024-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_auto_20240530_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleownership',
            old_name='lease_ending_date',
            new_name='purchase_date',
        ),
        migrations.RenameField(
            model_name='vehicleownership',
            old_name='lease_starting_date',
            new_name='rental_ending_date',
        ),
        migrations.AddField(
            model_name='vehicleownership',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicleownership',
            name='rental_starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleownership',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleownership',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
