# Generated by Django 3.2.22 on 2024-05-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_auto_20240530_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleownership',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='vehicleownership',
            name='starting_date',
        ),
    ]
