# Generated by Django 3.2.22 on 2024-05-31 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0038_auto_20240530_1526'),
        ('partnerships', '0008_auto_20240520_1043'),
        ('medias', '0011_file_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0017_auto_20240531_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMonthlyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('mileage', models.FloatField()),
                ('registration_card', models.CharField(choices=[('UP_TO_DATE', 'À jour'), ('UPDATE_SOON', 'Mettre à jour prochainement'), ('TO_UPDATE', 'À mettre à jour'), ('ABSENT', 'Absent')], default='UP_TO_DATE', max_length=20)),
                ('insurance_certificate', models.CharField(choices=[('UP_TO_DATE', 'À jour'), ('UPDATE_SOON', 'Mettre à jour prochainement'), ('TO_UPDATE', 'À mettre à jour'), ('ABSENT', 'Absent')], default='UP_TO_DATE', max_length=20)),
                ('insurance_attestation', models.CharField(choices=[('UP_TO_DATE', 'À jour'), ('UPDATE_SOON', 'Mettre à jour prochainement'), ('TO_UPDATE', 'À mettre à jour'), ('ABSENT', 'Absent')], default='UP_TO_DATE', max_length=20)),
                ('is_oil_level', models.BooleanField(default=False, null=True)),
                ('is_windshield_washer_level', models.BooleanField(default=False, null=True)),
                ('is_brake_fluid_level', models.BooleanField(default=False, null=True)),
                ('is_coolant_level', models.BooleanField(default=False, null=True)),
                ('is_tire_pressure', models.BooleanField(default=False, null=True)),
                ('is_lights_condition', models.BooleanField(default=False, null=True)),
                ('is_body_condition', models.BooleanField(default=False, null=True)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('controller_employees', models.ManyToManyField(to='human_ressources.Employee')),
                ('controller_partners', models.ManyToManyField(to='partnerships.Partner')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_monthly_inspections', to='vehicles.vehicle')),
            ],
        ),
    ]
