# Generated by Django 3.2.22 on 2024-05-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0008_auto_20240520_1043'),
        ('vehicles', '0018_vehiclemonthlyinspection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemonthlyinspection',
            old_name='inspection_date',
            new_name='inspection_date_time',
        ),
        migrations.RemoveField(
            model_name='vehiclemonthlyinspection',
            name='controller_partners',
        ),
        migrations.AddField(
            model_name='vehiclemonthlyinspection',
            name='controller_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_vehicles', to='partnerships.partner'),
        ),
        migrations.AlterField(
            model_name='vehiclemonthlyinspection',
            name='insurance_attestation',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemonthlyinspection',
            name='insurance_certificate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemonthlyinspection',
            name='registration_card',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleownership',
            name='expected_mileage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
