# Generated by Django 3.2.22 on 2024-05-31 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0008_auto_20240520_1043'),
        ('medias', '0011_file_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0038_auto_20240530_1526'),
        ('vehicles', '0019_auto_20240531_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date_time', models.DateField(blank=True, null=True)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('mileage', models.FloatField()),
                ('is_registration_card_here', models.BooleanField(default=False, null=True)),
                ('is_insurance_certificate_here', models.BooleanField(default=False, null=True)),
                ('is_insurance_attestation_here', models.BooleanField(default=False, null=True)),
                ('is_oil_level_ok', models.BooleanField(default=False, null=True)),
                ('is_windshield_washer_level_ok', models.BooleanField(default=False, null=True)),
                ('is_brake_fluid_level_ok', models.BooleanField(default=False, null=True)),
                ('is_coolant_level_ok', models.BooleanField(default=False, null=True)),
                ('is_tire_pressure_ok', models.BooleanField(default=False, null=True)),
                ('is_lights_condition_ok', models.BooleanField(default=False, null=True)),
                ('is_body_condition_ok', models.BooleanField(default=False, null=True)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('controller_employees', models.ManyToManyField(to='human_ressources.Employee')),
                ('controller_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_vehicles', to='partnerships.partner')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder')),
                ('images', models.ManyToManyField(related_name='image_vehicle_inspections', to='medias.File')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_inspections', to='vehicles.vehicle')),
                ('videos', models.ManyToManyField(related_name='video_vehicle_inspections', to='medias.File')),
            ],
        ),
        migrations.DeleteModel(
            name='VehicleMonthlyInspection',
        ),
    ]
