# Generated by Django 3.2.22 on 2024-05-31 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20240530_1515'),
        ('vehicles', '0022_vehicleinspection_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_inspected_vehicles', to='companies.company'),
        ),
    ]
