# Generated by Django 3.2.22 on 2024-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0023_vehicleinspection_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinspection',
            name='mileage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
