# Generated by Django 3.2.22 on 2024-06-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0024_alter_vehicleinspection_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='is_technical_control_here',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
