# Generated by Django 3.2.22 on 2024-06-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0025_vehicleinspection_is_technical_control_here'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinspection',
            name='inspection_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
