# Generated by Django 3.2.22 on 2024-06-04 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0030_vehicletechnicalinspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspectionFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_type', models.CharField(choices=[('MINOR', 'Défaillances mineur'), ('MAJOR', 'Défaillances majeur'), ('CRITICAL', 'Défaillances critique')], default='MINOR', max_length=50, null=True)),
                ('failure_text', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_inspection_failures', to=settings.AUTH_USER_MODEL)),
                ('vehicle_technical_inspection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='vehicles.vehicletechnicalinspection')),
            ],
        ),
    ]
