# Generated by Django 3.2.22 on 2024-06-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0031_vehicleinspectionfailure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleinspectionfailure',
            old_name='failure_text',
            new_name='description',
        ),
    ]
