# Generated by Django 3.2.22 on 2024-06-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0033_vehiclerepair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerepair',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
