# Generated by Django 3.2.22 on 2024-06-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0037_vehiclerepairvigilantpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='next_technical_inspection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionfailure',
            name='failure_type',
            field=models.CharField(choices=[('MINOR', 'Défaillance mineur'), ('MAJOR', 'Défaillance majeur'), ('CRITICAL', 'Défaillance critique')], default='MINOR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerepair',
            name='state',
            field=models.CharField(choices=[('COMPLETED', 'Terminée'), ('TO_DO', 'À faire')], default='COMPLETED', max_length=50, null=True),
        ),
    ]
