# Generated by Django 3.2.22 on 2024-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0038_auto_20240605_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerepair',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='vehicletechnicalinspection',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
