# Generated by Django 3.2.22 on 2024-09-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0040_alter_vehicle_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleownership',
            name='ownership_type',
            field=models.CharField(choices=[('LEASE', 'Location Longue Durée'), ('PURCHASE', 'Achat'), ('SALE', 'Vendu')], default='LEASE', max_length=10, null=True),
        ),
    ]
