# Generated by Django 3.2.22 on 2024-09-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0041_alter_vehicleownership_ownership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='state',
            field=models.CharField(choices=[('NEW', 'Neuf'), ('GOOD', 'En bon état'), ('BAD', 'Mauvais'), ('TO_REVIEW', 'À réviser'), ('IN_REPAIR', 'En réparation'), ('OUT_OF_SERVICE', 'Hors service')], default='GOOD', max_length=50, null=True),
        ),
    ]
