# Generated by Django 3.2.22 on 2024-09-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0043_alter_vehicleownership_ownership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleownership',
            name='rent_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
