# Generated by Django 3.2.22 on 2024-09-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0045_alter_vehicleownership_ownership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleownership',
            name='loan_details',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
