# Generated by Django 3.2.22 on 2024-09-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0046_vehicleownership_loan_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleownership',
            old_name='rent_sale_price',
            new_name='rent_purchase_price',
        ),
    ]
