# Generated by Django 3.2.22 on 2024-02-02 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0010_auto_20240201_1012'),
        ('partnerships', '0003_alter_partner_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.folder'),
        ),
    ]
