# Generated by Django 3.2.22 on 2024-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0004_partner_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.TextField(default='', null=True),
        ),
    ]
