# Generated by Django 3.2.22 on 2024-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0008_auto_20240520_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='financier',
            name='additional_address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_address',
            field=models.TextField(default='', null=True),
        ),
    ]
