# Generated by Django 3.2.22 on 2025-03-07 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_alter_establishment_measurement_activity_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partnerships', '0009_auto_20241212_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='companies.establishment')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to='partnerships.partner')),
            ],
        ),
    ]
