# Generated by Django 3.2.22 on 2025-03-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_alter_establishment_measurement_activity_unit'),
        ('partnerships', '0010_partnerestablishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerestablishment',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.establishment'),
        ),
    ]
