# Generated by Django 3.2.22 on 2024-01-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectrecovery',
            name='the_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='the_object_recoveries', to='loan_management.theobject'),
        ),
    ]
