# Generated by Django 3.2.22 on 2025-05-13 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0042_company_approval_number'),
        ('data_management', '0052_employeeposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('LEAVE', 'Demande de congé'), ('EXPENSE', 'Note de frais'), ('TASK', 'Demande d’intervention')], max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_workflows', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_workflows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('role_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('service_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('validator_type', models.CharField(choices=[('ROLE', 'Rôle'), ('POSITION', 'Poste spécifique'), ('MANAGER', 'Manager du demandeur')], max_length=20)),
                ('required_approval_count', models.PositiveIntegerField(default=1)),
                ('condition_expression', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_steps', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.employeeposition')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.validationworkflow')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='FallbackRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallback_type', models.CharField(choices=[('REPLACEMENT', 'Remplaçant déclaré'), ('HIERARCHY', 'Supérieur hiérarchique'), ('ADMIN', 'Notifier l’administrateur')], max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_rules', to=settings.AUTH_USER_MODEL)),
                ('fallback_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.employeeposition')),
                ('fallback_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallbacks', to='workflow.validationstep')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
