# Generated by Django 3.2.22 on 2025-05-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationworkflow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
