# Generated by Django 3.2.22 on 2025-05-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_validationworkflow_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationworkflow',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='validationworkflow',
            name='observation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='fallbackrule',
            name='fallback_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='validationstep',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
