# Generated by Django 3.2.22 on 2025-05-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0089_alter_employee_company'),
        ('data_management', '0052_employeeposition'),
        ('workflow', '0003_auto_20250514_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fallbackrule',
            name='step',
        ),
        migrations.AddField(
            model_name='fallbackrule',
            name='validation_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallback_rules', to='workflow.validationstep'),
        ),
        migrations.AlterField(
            model_name='validationstep',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_steps', to='workflow.validationworkflow'),
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(blank=True, max_length=100, null=True)),
                ('target_service', models.CharField(blank=True, max_length=100, null=True)),
                ('validator_role', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_ressources.employee')),
                ('validation_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='workflow.validationstep')),
                ('validator_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_as_validator', to='human_ressources.employee')),
                ('validator_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.employeeposition')),
            ],
        ),
    ]
