# Generated by Django 3.2.22 on 2025-05-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0052_employeeposition'),
        ('human_ressources', '0089_alter_employee_company'),
        ('workflow', '0004_auto_20250514_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fallbackrule',
            name='fallback_position',
        ),
        migrations.RemoveField(
            model_name='fallbackrule',
            name='fallback_role',
        ),
        migrations.RemoveField(
            model_name='validationrule',
            name='target_employee',
        ),
        migrations.RemoveField(
            model_name='validationrule',
            name='target_role',
        ),
        migrations.RemoveField(
            model_name='validationrule',
            name='target_service',
        ),
        migrations.RemoveField(
            model_name='validationrule',
            name='validator_employee',
        ),
        migrations.RemoveField(
            model_name='validationrule',
            name='validator_position',
        ),
        migrations.RemoveField(
            model_name='validationrule',
            name='validator_role',
        ),
        migrations.RemoveField(
            model_name='validationstep',
            name='position',
        ),
        migrations.RemoveField(
            model_name='validationstep',
            name='role',
        ),
        migrations.RemoveField(
            model_name='validationstep',
            name='role_condition',
        ),
        migrations.RemoveField(
            model_name='validationstep',
            name='service_condition',
        ),
        migrations.AddField(
            model_name='fallbackrule',
            name='fallback_employees',
            field=models.ManyToManyField(blank=True, related_name='fallback_rules', to='human_ressources.Employee'),
        ),
        migrations.AddField(
            model_name='fallbackrule',
            name='fallback_positions',
            field=models.ManyToManyField(blank=True, related_name='fallback_rules', to='data_management.EmployeePosition'),
        ),
        migrations.AddField(
            model_name='fallbackrule',
            name='fallback_roles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='target_employees',
            field=models.ManyToManyField(blank=True, related_name='rules_as_target_employee', to='human_ressources.Employee'),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='target_roles',
            field=models.JSONField(blank=True, help_text='Liste des rôles des demandeurs concernés (format JSON)', null=True),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='target_services',
            field=models.JSONField(blank=True, help_text='Liste des services des demandeurs concernés (format JSON)', null=True),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='validator_employees',
            field=models.ManyToManyField(blank=True, related_name='rules_as_validator_employee', to='human_ressources.Employee'),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='validator_positions',
            field=models.ManyToManyField(blank=True, related_name='rules_as_validator_position', to='data_management.EmployeePosition'),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='validator_roles',
            field=models.JSONField(blank=True, help_text='Liste des rôles des validateurs (format JSON)', null=True),
        ),
        migrations.AddField(
            model_name='validationstep',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='validation_steps', to='human_ressources.Employee'),
        ),
        migrations.AddField(
            model_name='validationstep',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='validation_steps', to='data_management.EmployeePosition'),
        ),
        migrations.AddField(
            model_name='validationstep',
            name='role_conditions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationstep',
            name='roles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationstep',
            name='service_conditions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
