# Generated by Django 3.2.22 on 2025-05-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20250514_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validationstep',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='validationstep',
            old_name='step_order',
            new_name='order',
        ),
    ]
