# Generated by Django 3.2.22 on 2025-05-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_auto_20250514_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationstep',
            old_name='condition_expression',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='validationstep',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='validationstep',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='validationstep',
            name='required_approval_count',
        ),
        migrations.RemoveField(
            model_name='validationstep',
            name='role_conditions',
        ),
        migrations.RemoveField(
            model_name='validationstep',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='validationstep',
            name='service_conditions',
        ),
        migrations.RemoveField(
            model_name='validationstep',
            name='validator_type',
        ),
        migrations.AddField(
            model_name='validationrule',
            name='condition_expression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='validator_type',
            field=models.CharField(choices=[('ROLE', 'Rôle'), ('POSITION', 'Poste spécifique'), ('MANAGER', 'Manager du demandeur')], default='ROLE', max_length=20),
        ),
    ]
