# Generated by Django 3.2.22 on 2025-05-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0052_employeeposition'),
        ('human_ressources', '0090_employeegroupmanager'),
        ('workflow', '0007_auto_20250519_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationrule',
            name='target_services',
        ),
        migrations.AddField(
            model_name='validationrule',
            name='target_employee_groups',
            field=models.ManyToManyField(blank=True, related_name='rules_as_target_employee_group', to='human_ressources.EmployeeGroup'),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='target_positions',
            field=models.ManyToManyField(blank=True, related_name='rules_as_target_position', to='data_management.EmployeePosition'),
        ),
    ]
