# Generated by Django 3.2.22 on 2025-05-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20250519_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='validator_type',
            field=models.CharField(choices=[('ROLE', 'Rôle'), ('POSITION', 'Poste spécifique'), ('MANAGER', 'Manager du demandeur'), ('CUSTOM', 'Sélection personnalisée')], default='ROLE', max_length=20),
        ),
    ]
