# Generated by Django 3.2.22 on 2025-05-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_alter_validationrule_validator_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationstep',
            old_name='workflow',
            new_name='validation_workflow',
        ),
    ]
