# Generated by Django 3.2.22 on 2023-10-26 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('bar_code', models.CharField(max_length=255)),
                ('is_blocked', models.BooleanField(null=True)),
                ('is_stock_auto', models.BooleanField(null=True)),
                ('designation', models.TextField()),
                ('buying_price_ht', models.FloatField(null=True)),
                ('tva', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('observation', models.TextField()),
                ('is_active', models.BooleanField(null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_image', to='medias.file')),
            ],
        ),
    ]
