# Generated by Django 3.2.22 on 2025-04-08 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0085_employee_job_candidate'),
        ('stocks', '0008_material_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('return_due_date', models.DateField(blank=True, null=True)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('returned_quantity', models.PositiveIntegerField(blank=True, help_text='Quantité réellement retournée', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_assignments', to='human_ressources.employee')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stocks.material')),
            ],
        ),
    ]
