# Generated by Django 3.2.22 on 2023-12-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'Système'), ('ADDED_TO_TASK', 'Affecté à une intérvention'), ('GO_TO_TASK', "Départ vers l'intérvention"), ('TASK_STARTED', "L'intérvention commencée"), ('TASK_FINISHED', "L'intérvention terminée")], default='SYSTEM', max_length=50),
        ),
    ]
