# Generated by Django 3.2.22 on 2024-06-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20240530_1515'),
        ('notifications', '0006_notification_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_notification_type', models.CharField(choices=[('SYSTEM', 'System'), ('REMINDER', 'Reminder'), ('MESSAGE', 'Message'), ('TASK', 'Task'), ('EVENT', 'Event'), ('NEWS', 'News'), ('WARNING', 'Warning'), ('PROMOTION', 'Promotion'), ('UPDATE', 'Update'), ('FEEDBACK', 'Feedback'), ('ERROR', 'Error')], default='SYSTEM', max_length=50)),
                ('title', models.CharField(max_length=255, null=True)),
                ('message', models.TextField(null=True)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('is_seen', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_notifications', to='companies.company')),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_notifications', to='companies.establishment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
