# Generated by Django 3.2.22 on 2024-06-29 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20240530_1515'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0007_messagenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagenotification',
            name='establishment',
        ),
        migrations.CreateModel(
            name='MessageNotificationEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_notification_establishments', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_notification_establishments', to='companies.establishment')),
                ('message_notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to='notifications.messagenotification')),
            ],
        ),
    ]
