# Generated by Django 3.2.22 on 2024-06-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0011_file_company'),
        ('notifications', '0008_auto_20240629_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenotification',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_notifications', to='medias.file'),
        ),
    ]
