# Generated by Django 3.2.22 on 2024-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_messagenotification_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagenotification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='messagenotification',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='messagenotification',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagenotification',
            name='message_notification_type',
            field=models.CharField(choices=[('SYSTEM', 'Système'), ('REMINDER', 'Rappel'), ('MESSAGE', 'Message'), ('TASK', 'Tâche'), ('EVENT', 'Événement'), ('NEWS', 'Actualités'), ('WARNING', 'Avertissement'), ('PROMOTION', 'Promotion'), ('UPDATE', 'Mise à jour'), ('FEEDBACK', 'Commentaires'), ('ERROR', 'Erreur')], default='SYSTEM', max_length=50),
        ),
    ]
