# Generated by Django 3.2.22 on 2024-07-01 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualities', '0043_undesirableevent_call'),
        ('notifications', '0011_messagenotification_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='undesirable_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='qualities.undesirableevent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'Système'), ('ADDED_TO_TASK', 'Affecté à une intérvention'), ('GO_TO_TASK', "Départ vers l'intérvention"), ('TASK_STARTED', "L'intérvention commencée"), ('TASK_FINISHED', "L'intérvention terminée"), ('EI_ADDED', 'Événement indésirable déclaré')], default='SYSTEM', max_length=50),
        ),
    ]
