# Generated by Django 3.2.22 on 2024-07-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0033_auto_20240627_1107'),
        ('notifications', '0012_auto_20240701_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='works.taskaction'),
        ),
    ]
