# Generated by Django 3.2.22 on 2024-07-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administratives', '0039_auto_20240628_0959'),
        ('notifications', '0014_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meeting_decision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='administratives.meetingdecision'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'Système'), ('ADDED_TO_TASK', 'Affecté à une intérvention'), ('GO_TO_TASK', "Départ vers l'intérvention"), ('TASK_STARTED', "L'intérvention commencée"), ('TASK_FINISHED', "L'intérvention terminée"), ('EI_ADDED', 'Événement indésirable déclaré'), ('TASK_ACTION_ADDED', 'Affecté à une action'), ('MEETING_DECISION_ADDED', 'Affecté à une décision')], default='SYSTEM', max_length=50),
        ),
    ]
