# Generated by Django 3.2.22 on 2024-07-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_employeeabsence_message'),
        ('notifications', '0015_auto_20240701_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='employee_absence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='planning.employeeabsence'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'Système'), ('ADDED_TO_TASK', 'Affecté à une intérvention'), ('GO_TO_TASK', "Départ vers l'intérvention"), ('TASK_STARTED', "L'intérvention commencée"), ('TASK_FINISHED', "L'intérvention terminée"), ('EI_ADDED', 'Événement indésirable déclaré'), ('TASK_ACTION_ADDED', 'Affecté à une action'), ('MEETING_DECISION_ADDED', 'Affecté à une décision'), ('EMPLOYEE_ABSENCE_ADDED', 'Nouvelle demande de congé ajoutée'), ('EMPLOYEE_ABSENCE_UPDATED', 'Demande de congé mise à jour'), ('EMPLOYEE_ABSENCE_PENDING', 'Demande de congé en attente de décision'), ('EMPLOYEE_ABSENCE_APPROVED', 'Demande de congé approuvée'), ('EMPLOYEE_ABSENCE_REJECTED', 'Demande de congé rejetée')], default='SYSTEM', max_length=50),
        ),
    ]
