# Generated by Django 3.2.22 on 2024-07-09 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0017_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotificationUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('message_notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_notification_statuses', to='notifications.messagenotification')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_notification_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message_notification', 'user')},
            },
        ),
    ]
