# Generated by Django 3.2.22 on 2024-09-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagenotification',
            name='message_notification_type',
            field=models.CharField(choices=[('SYSTEM', 'Système'), ('REMINDER', 'Rappel'), ('MESSAGE', 'Message'), ('TASK', 'Tâche'), ('SCE', 'Cse'), ('EVENT', 'Événement'), ('NEWS', 'Actualités'), ('WARNING', 'Avertissement'), ('PROMOTION', 'Promotion'), ('UPDATE', 'Mise à jour'), ('FEEDBACK', 'Commentaires'), ('ERROR', 'Erreur')], default='SYSTEM', max_length=50),
        ),
    ]
