# Generated by Django 3.2.22 on 2025-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0025_auto_20241227_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenotification',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
