# Generated by Django 3.2.22 on 2025-04-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0026_messagenotification_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'Système'), ('TASK_ADDED', 'Nouvelle intervention ajoutée'), ('TASK_UPDATED', 'Intervention mise à jour'), ('TASK_PENDING', 'Intervention en attente de décision'), ('TASK_APPROVED', 'Intervention approuvée'), ('TASK_REJECTED', 'Intervention rejetée'), ('ADDED_TO_TASK', 'Affecté à une intérvention'), ('TASK_TO_DO', 'Affecté à une intérvention'), ('GO_TO_TASK', "Départ vers l'intérvention"), ('TASK_STARTED', "L'intérvention commencée"), ('TASK_IN_PROGRESS', "L'intérvention commencée"), ('TASK_FINISHED', "L'intérvention terminée"), ('TASK_COMPLETED', "L'intérvention terminée"), ('EI_ADDED', 'Événement indésirable déclaré'), ('EI_UPDATED', 'Événement indésirable mise à jour'), ('EI_NEW', 'Événement indésirable remis comme déclaré'), ('EI_IN_PROGRESS', 'Événement indésirable en cours de traitement'), ('EI_DONE', 'Événement indésirable traité'), ('TASK_ACTION_ADDED', 'Affecté à une action'), ('MEETING_DECISION_ADDED', 'Affecté à une décision'), ('EMPLOYEE_ABSENCE_ADDED', 'Nouvelle demande de congé ajoutée'), ('EMPLOYEE_ABSENCE_UPDATED', 'Demande de congé mise à jour'), ('EMPLOYEE_ABSENCE_PENDING', 'Demande de congé en attente de décision'), ('EMPLOYEE_ABSENCE_APPROVED', 'Demande de congé approuvée'), ('EMPLOYEE_ABSENCE_REJECTED', 'Demande de congé rejetée'), ('EMPLOYEE_ABSENCE_NOT_JUSTIFIED', 'Absence non justifiée'), ('EMPLOYEE_ABSENCE_TO_JUSTIFY', "Justification d'absence requise"), ('EMPLOYEE_ABSENCE_JUSTIFIED', 'Absence justifiée'), ('EXPENSE_ADDED', 'Nouvelle demande de dépense ajoutée'), ('EXPENSE_UPDATED', 'Demande de dépense mise à jour'), ('EXPENSE_PENDING', "Demande de dépense en attente d'approbation"), ('EXPENSE_APPROVED', 'Demande de dépense approuvée'), ('EXPENSE_REJECTED', 'Demande de dépense rejetée'), ('EXPENSE_PAID', 'Dépense payée.'), ('EXPENSE_UNPAID', 'Dépense non payée.'), ('EXPENSE_REPORT_ADDED', 'Nouvelle demande de remboursement de note de frais ajoutée'), ('EXPENSE_REPORT_UPDATED', 'Demande de remboursement de note de frais mise à jour'), ('EXPENSE_REPORT_PENDING', "Demande de remboursement de note de frais en attente d'approbation"), ('EXPENSE_REPORT_APPROVED', 'Demande de remboursement de note de frais approuvée'), ('EXPENSE_REPORT_REJECTED', 'Demande de remboursement de note de frais rejetée'), ('EXPENSE_REPORT_REIMBURSED', 'Note de frais remboursée.'), ('BENEFICIARY_ADMISSION_ADDED', "Nouvelle demande d'admission ajoutée"), ('BENEFICIARY_ADMISSION_UPDATED', "Demande d'admission mise à jour"), ('BENEFICIARY_ADMISSION_PENDING', "Demande d'admission en attente"), ('BENEFICIARY_ADMISSION_APPROVED', "Demande d'admission approuvée"), ('BENEFICIARY_ADMISSION_REJECTED', "Demande d'admission rejetée"), ('BENEFICIARY_ADMISSION_CANCELED', "Demande d'admission annulée")], default='SYSTEM', max_length=50),
        ),
    ]
