# Generated by Django 3.2.22 on 2023-10-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_task_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ending_date',
            new_name='ending_date_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='starting_date',
            new_name='starting_date_time',
        ),
    ]
