# Generated by Django 3.2.22 on 2023-10-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20231030_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskparticipant',
            name='latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskparticipant',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
