# Generated by Django 3.2.22 on 2023-10-30 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_ressources', '0005_auto_20231024_1233'),
        ('works', '0005_auto_20231030_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_worker_former', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_employee', to='human_ressources.employee')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.task')),
            ],
        ),
        migrations.AddField(
            model_name='taskmaterial',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='TaskParticipant',
        ),
    ]
