# Generated by Django 3.2.22 on 2023-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_taskchecklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecklistitem',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='taskchecklistitem',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskchecklistitem',
            name='observation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='taskchecklistitem',
            name='status',
            field=models.CharField(choices=[('NEW', 'A faire'), ('STARTED', 'En cours'), ('FINISHED', 'Terminée'), ('PENDING', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='NEW', max_length=50),
        ),
    ]
