# Generated by Django 3.2.22 on 2023-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_auto_20231109_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstep',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
