# Generated by Django 3.2.22 on 2023-11-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_auto_20231114_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstep',
            name='status',
            field=models.CharField(choices=[('NEW', 'A faire'), ('STARTED', 'En cours'), ('FINISHED', 'Terminée'), ('PENDING', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='PENDING', max_length=50),
        ),
    ]
