# Generated by Django 3.2.22 on 2023-11-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_signature'),
        ('works', '0011_taskstep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_client_signature', to='feedbacks.signature'),
        ),
        migrations.AddField(
            model_name='task',
            name='employee_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_employee_signature', to='feedbacks.signature'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'À faire'), ('STARTED', 'En cours'), ('FINISHED', 'Terminée'), ('PENDING', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskchecklistitem',
            name='status',
            field=models.CharField(choices=[('NEW', 'À faire'), ('STARTED', 'En cours'), ('FINISHED', 'Terminée'), ('PENDING', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='status',
            field=models.CharField(choices=[('NEW', 'À faire'), ('STARTED', 'En cours'), ('FINISHED', 'Terminée'), ('PENDING', 'En attente'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='PENDING', max_length=50),
        ),
    ]
