# Generated by Django 3.2.22 on 2023-12-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_auto_20231129_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmaterial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taskvehicle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taskworker',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='taskworker',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='taskworker',
            name='name',
        ),
    ]
