# Generated by Django 3.2.22 on 2023-12-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_auto_20231201_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='google_calendar_event_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
