# Generated by Django 3.2.22 on 2024-01-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_auto_20231208_0914'),
        ('works', '0015_task_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstep',
            name='comments',
            field=models.ManyToManyField(related_name='task_step', to='feedbacks.Comment'),
        ),
    ]
