# Generated by Django 3.2.22 on 2024-01-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_alter_taskstep_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='discount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='total_ht',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='total_ttc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tva',
            field=models.FloatField(default=0, null=True),
        ),
    ]
