# Generated by Django 3.2.22 on 2024-01-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0017_auto_20240122_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='total_ht',
            new_name='total_price_ht',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='total_ttc',
            new_name='total_price_ttc',
        ),
        migrations.AddField(
            model_name='task',
            name='is_display_price',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
