# Generated by Django 3.2.22 on 2024-01-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0018_auto_20240122_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_from_quote',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
