# Generated by Django 3.2.22 on 2024-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0019_task_is_from_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskchecklistitem',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
