# Generated by Django 3.2.22 on 2024-02-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0020_auto_20240130_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
