# Generated by Django 3.2.22 on 2024-02-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0023_auto_20240220_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_task_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
