# Generated by Django 3.2.22 on 2024-02-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0026_auto_20240220_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='site_owner_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='site_tenant_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
