# Generated by Django 3.2.22 on 2024-02-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0027_auto_20240220_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
