# Generated by Django 3.2.22 on 2024-06-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0010_statuschange'),
        ('works', '0031_taskaction_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.ManyToManyField(related_name='tickets', to='feedbacks.Comment'),
        ),
    ]
