# Generated by Django 3.2.22 on 2024-06-27 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20240530_1515'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0032_ticket_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='billing_address',
            new_name='additional_address',
        ),
        migrations.RemoveField(
            model_name='task',
            name='client',
        ),
        migrations.RemoveField(
            model_name='task',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='client_signature',
        ),
        migrations.RemoveField(
            model_name='task',
            name='client_task_number',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contractor_email',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contractor_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contractor_tel',
        ),
        migrations.RemoveField(
            model_name='task',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee_signature',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_budget',
        ),
        migrations.RemoveField(
            model_name='task',
            name='fix',
        ),
        migrations.RemoveField(
            model_name='task',
            name='google_calendar_event_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_display_price',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_from_quote',
        ),
        migrations.RemoveField(
            model_name='task',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='task',
            name='site_owner_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='site_tenant_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
        migrations.RemoveField(
            model_name='task',
            name='total_price_ht',
        ),
        migrations.RemoveField(
            model_name='task',
            name='total_price_ttc',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tva',
        ),
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'À faire'), ('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('TO_DO', 'À fair'), ('IN_PROGRESS', 'En attente'), ('COMPLETED', 'Terminée'), ('CANCELED', 'Annulée'), ('ARCHIVED', 'Archivée')], default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskchecklistitem',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_checklist', to='works.task'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='works.task'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_steps', to='works.task'),
        ),
        migrations.AlterField(
            model_name='taskvehicle',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='works.task'),
        ),
        migrations.AlterField(
            model_name='taskworker',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='works.task'),
        ),
        migrations.CreateModel(
            name='TaskEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_establishments', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_establishments', to='companies.establishment')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to='works.task')),
            ],
        ),
    ]
