# Generated by Django 3.2.22 on 2024-07-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0034_efcreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_have_efc_report',
            field=models.BooleanField(default=False),
        ),
    ]
