# Generated by Django 3.2.22 on 2024-07-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressources', '0051_alter_employeecontract_contract_type'),
        ('works', '0035_ticket_is_have_efc_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_tasks', to='human_ressources.employee'),
        ),
    ]
