# Generated by Django 3.2.22 on 2024-10-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0036_task_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comments',
        ),
    ]
