# Generated by Django 3.2.22 on 2024-10-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0037_remove_ticket_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskaction',
            name='is_archived',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='taskaction',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
