# Generated by Django 3.2.22 on 2024-12-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0039_taskaction_meeting_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('PLAN_ACTION', "Plan d'action"), ('LUP', "Levée d'une non-conformité"), ('IT_SUPPORT', 'Support informatique'), ('GENERAL', 'Général')], default='PLAN_ACION', max_length=50),
        ),
    ]
