# Generated by Django 3.2.22 on 2025-04-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0042_auto_20250123_1128'),
        ('works', '0041_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='purchases.supplier'),
        ),
    ]
