# Generated by Django 3.2.22 on 2024-05-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_establishmentservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstablishmentService',
        ),
    ]
