# Generated by Django 3.2.22 on 2024-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='additional_address',
            field=models.TextField(default='', null=True),
        ),
    ]
