# Generated by Django 3.2.22 on 2025-01-09 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0009_auto_20241212_1520'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0035_companymedia_blog_url'),
        ('human_ressources', '0064_beneficiaryadmission_status_reason'),
        ('sales', '0011_client_additional_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('invoice_type', models.CharField(choices=[('STANDARD', 'Facture Standard'), ('DEPOSIT', "Facture d'Acompte")], default='STANDARD', max_length=50)),
                ('title', models.TextField(default='', null=True)),
                ('description', models.TextField(default='', null=True)),
                ('client_number', models.CharField(max_length=255)),
                ('client_tva_number', models.CharField(max_length=255, null=True)),
                ('client_address', models.TextField(default='', null=True)),
                ('client_name', models.CharField(max_length=255, null=True)),
                ('client_city', models.CharField(max_length=255, null=True)),
                ('client_country', models.CharField(max_length=255, null=True)),
                ('client_zip_code', models.CharField(max_length=255, null=True)),
                ('client_mobile', models.CharField(max_length=255, null=True)),
                ('client_fix', models.CharField(max_length=255, null=True)),
                ('client_email', models.EmailField(max_length=254, null=True)),
                ('emission_date', models.DateTimeField(null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('validity_end_date', models.DateTimeField(null=True)),
                ('payment_date', models.DateTimeField(null=True)),
                ('comment', models.TextField(default='', null=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('CREDIT_CARD', 'Carte de crédit'), ('BANK_TRANSFER', 'Virement bancaire'), ('DIRECT_DEBIT', 'Prélèvement'), ('PAYPAL', 'PayPal'), ('CHECK', 'Chèque'), ('BILL_OF_EXCHANGE', 'Lettre de change relevé'), ('LIBEO_TRANSFER', 'Virement par Libeo'), ('MOBILE_PAYMENT', 'Paiement mobile'), ('CRYPTOCURRENCY', 'Cryptomonnaie'), ('DEBIT_CARD', 'Carte de débit'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay')], default='BANK_TRANSFER', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validée'), ('PARTIALLY_PAID', 'Semi Réglée'), ('PAID', 'Réglée'), ('CANCELED', 'Annulée')], default='DRAFT', max_length=50)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='companies.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='companies.establishment')),
                ('financier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnerships.financier')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(default='', null=True)),
                ('name', models.TextField(default='', null=True)),
                ('designation', models.TextField(default='', null=True)),
                ('description', models.TextField(default='', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('quantity', models.FloatField(default=1, null=True)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='human_ressources.beneficiary')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='sales.invoice')),
            ],
        ),
    ]
