# Generated by Django 3.2.22 on 2025-01-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
