# Generated by Django 3.2.22 on 2025-01-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0045_auto_20250103_1608'),
        ('companies', '0035_companymedia_blog_url'),
        ('sales', '0013_auto_20250109_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='name',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='companies.establishment'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='establishment_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.humangender'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='preferred_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
