# Generated by Django 3.2.22 on 2025-01-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20250109_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='establishment_address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_fix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_tva_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_zip_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
