# Generated by Django 3.2.22 on 2025-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20250109_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='measurement_unit',
            field=models.CharField(choices=[('DAY', 'Jour'), ('HOUR', 'Heure'), ('MONTH', 'Mois')], default='DAY', max_length=50),
        ),
    ]
