# Generated by Django 3.2.22 on 2025-01-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20250110_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='month',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
