# Generated by Django 3.2.22 on 2025-01-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0035_companymedia_blog_url'),
        ('sales', '0018_auto_20250110_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='establishments',
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='companies.establishment'),
        ),
    ]
