# Generated by Django 3.2.22 on 2025-01-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20250113_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='signature',
            new_name='signatures',
        ),
    ]
