# Generated by Django 3.2.22 on 2025-01-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_rename_signature_invoice_signatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_deposit',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='validity_end_date',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='gender',
        ),
    ]
