# Generated by Django 3.2.22 on 2025-01-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_auto_20250113_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='establishment_capacity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
