# Generated by Django 3.2.22 on 2025-01-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_auto_20250113_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_infos',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_infos',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
