# Generated by Django 3.2.22 on 2025-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_auto_20250113_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_bic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_iban',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_bic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_iban',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='establishment_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
