# Generated by Django 3.2.22 on 2025-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_auto_20250115_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_logo_base64_encoded',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_ape_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_finess',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_logo_base64_encoded',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_siret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
