# Generated by Django 3.2.22 on 2025-03-31 09:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0037_auto_20250324_1229'),
        ('sales', '0029_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='client_address',
            new_name='financier_address',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_bank_name',
            new_name='financier_bank_name',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_bic',
            new_name='financier_bic',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_city',
            new_name='financier_city',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_country',
            new_name='financier_country',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_email',
            new_name='financier_email',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_fix',
            new_name='financier_fix',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_iban',
            new_name='financier_iban',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_infos',
            new_name='financier_infos',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_logo_base64_encoded',
            new_name='financier_logo_base64_encoded',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_mobile',
            new_name='financier_mobile',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_name',
            new_name='financier_name',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_number',
            new_name='financier_number',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_tva_number',
            new_name='financier_tva_number',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_zip_code',
            new_name='financier_zip_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_ape_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_bank_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_bic',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_capacity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_city',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_country',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_finess',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_fix',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_iban',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_infos',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_logo_base64_encoded',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_mobile',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_siret',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_tva_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='establishment_zip_code',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='establishment_name',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='establishment_number',
        ),
        migrations.CreateModel(
            name='InvoiceEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_logo_base64_encoded', models.TextField(null=True)),
                ('establishment_infos', models.CharField(max_length=255, null=True)),
                ('establishment_number', models.CharField(max_length=255, null=True)),
                ('establishment_name', models.CharField(max_length=255, null=True)),
                ('establishment_siret', models.CharField(max_length=255, null=True)),
                ('establishment_finess', models.CharField(max_length=255, null=True)),
                ('establishment_ape_code', models.CharField(max_length=255, null=True)),
                ('establishment_tva_number', models.CharField(max_length=255, null=True)),
                ('establishment_capacity', models.FloatField(null=True)),
                ('establishment_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11, null=True)),
                ('establishment_address', models.TextField(default='', null=True)),
                ('establishment_city', models.CharField(max_length=255, null=True)),
                ('establishment_country', models.CharField(max_length=255, null=True)),
                ('establishment_zip_code', models.CharField(max_length=255, null=True)),
                ('establishment_mobile', models.CharField(max_length=255, null=True)),
                ('establishment_fix', models.CharField(max_length=255, null=True)),
                ('establishment_email', models.EmailField(max_length=254, null=True)),
                ('establishment_iban', models.CharField(max_length=255, null=True)),
                ('establishment_bic', models.CharField(max_length=255, null=True)),
                ('establishment_bank_name', models.CharField(max_length=255, null=True)),
                ('comment', models.TextField(default='', null=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11, null=True)),
                ('tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11, null=True)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('CREDIT_CARD', 'Carte de crédit'), ('BANK_TRANSFER', 'Virement bancaire'), ('DIRECT_DEBIT', 'Prélèvement'), ('PAYPAL', 'PayPal'), ('CHECK', 'Chèque'), ('BILL_OF_EXCHANGE', 'Lettre de change relevé'), ('LIBEO_TRANSFER', 'Virement par Libeo'), ('MOBILE_PAYMENT', 'Paiement mobile'), ('CRYPTOCURRENCY', 'Cryptomonnaie'), ('DEBIT_CARD', 'Carte de débit'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay')], default='BANK_TRANSFER', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_establishments', to='companies.establishment')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_establishments', to='sales.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice_establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='sales.invoiceestablishment'),
        ),
    ]
