# Generated by Django 3.2.22 on 2025-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_alter_invoiceitem_invoice_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_account_number',
            field=models.CharField(max_length=11, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_ape_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_bank_code',
            field=models.CharField(max_length=5, null=True, verbose_name='Bank Code'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_branch_code',
            field=models.CharField(max_length=5, null=True, verbose_name='Branch Code'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_finess',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_rib_key',
            field=models.CharField(max_length=2, null=True, verbose_name='RIB Key'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_siret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
