# Generated by Django 3.2.22 on 2025-05-07 14:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_invoice_company_approval_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='establishment_address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_ape_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_bic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_capacity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_finess',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_fix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_iban',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_infos',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_logo_base64_encoded',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_siret',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_tva_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='establishment_zip_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
